### ISSUE TITLE
log all calls

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#102]
am I just being blind, or has the ability to log all method calls been removed in v3 of scalamock?

As part of #101 I'd like to log every method that is called, and what the response is (which, admittedly, would probably hit some kind of thread boundary and make the problem go away if this is a scalamock problem)..

**Comment by paulbutcher** [comment]
Oops! I fear you're right (interesting that nobody's noticed until now!).

**Comment by fommil** [comment]
that makes a change. Hunting down this transient in my code is making me feel like I don't know anything about anything! :smile:

**Comment by paulbutcher** [comment]
Which does raise an interesting point—adding the synchronisation that I alluded to in my comment on #101 would certainly mean that using ScalaMock in multi-threaded tests would change the synchronisation properties of the system under test, making multi-threaded tests less likely to fail if the system under test is incorrectly synchronised.

(in fact, this is already true, but the approach I'm thinking about would increase the magnitude of the effect).

**Comment by fommil** [comment]
Indeed, but surely that's a problem with the synchronisation of the thing that's being mocked not the thing that's being tested. I should imagine that only integration tests would catch that sort of thing, if it is not tested at the unit level.

**Comment by barkhorn** [comment]
PR #165

**Comment by barkhorn** [comment]
example:

```
      val m = mock[TestTrait]

      inAnyOrderWithLogging {
        m.oneParam _ expects * twice()
      }
      inSequenceWithLogging {
        m.twoParams _ expects(*, *) once()
        (m.overloaded(_: Int)) expects * once()
      }
```
