### ISSUE TITLE
Stub ordered matching behaves different than mock matching

### ISSUE THREAD

**Issue by gzm0** [paulbutcher/ScalaMock#107]
Consider the following example:

``` scala
import org.scalatest.FunSuite
import org.scalamock.scalatest.MockFactory

class MatcherTest extends FunSuite with MockFactory {

  trait Comp {
    def create(): Int
    def destroy(i: Int): Unit
  }

  def methodUnderTest(comp: Comp) = {
    val c1 = comp.create()
    val c2 = comp.create()
    comp.destroy(c1)
    comp.destroy(c2)
  }

  test("mock style") {
    val comp = mock[Comp]

    def compCycle(i: Int) = inSequence {
      (comp.create _).expects().returning(i)
      (comp.destroy _).expects(i)
    }

    compCycle(0)
    compCycle(1)

    methodUnderTest(comp)
  }

  test("stub style") {
    val comp = stub[Comp]

    var cid = 0

    (comp.create _).when().onCall { () => cid += 1; cid }

    methodUnderTest(comp)

    def compCycle(i: Int) = inSequence {
      (comp.create _).verify().returning(i)
      (comp.destroy _).verify(i)
    }

    (1 to cid).foreach(compCycle)
  }
}
```

While I expect both tests to pass, the second one fails:

```
MatcherTest:
- mock style
- stub style *** FAILED ***
  Unsatisfied expectation:

  Expected:
  inAnyOrder {
    create() any number of times (called twice)
    inSequence {
      create() once (called twice - UNSATISFIED)
      destroy(1) once (called once)
    }
    inSequence {
      create() once (never called - UNSATISFIED)
      destroy(2) once (called once)
    }
  }

  Actual:
    create()
    create()
    destroy(1)
    destroy(2) (MatcherTest.scala:4)
```

I would expect the second one to pass as well since there is a way to match the expectations on the sequence of the calls.

**Comment by gzm0** [comment]
Fails with both ScalaMock 3.2 and ScalaMock 3.2.1

**Comment by pawel-wiejacha** [comment]
@gzm0 Thanks for catching this bug

Here's more readable (IMO) version of the second test case:
```scala

  test("stub style - clean one") {
    val comp = stub[Comp]

    (comp.create _).when().returns(0).once
    (comp.create _).when().returns(1).once

    methodUnderTest(comp)

    def compCycle(i: Int) = inSequence {
      (comp.create _).verify().returning(i)
      (comp.destroy _).verify(i)
    }

    compCycle(0)
    compCycle(1)
  }
```

**Comment by gzm0** [comment]
This is indeed more readable. The other version has the advantage of being agnostic to the number of invocations (which is what I am trying to aim for), but for this simple case, this is indeed easier to understand.

**Comment by pawel-wiejacha** [comment]
I don't know yet how to fix it gracefully. `CallHandler.isExhausted` must be checked during *stub* verification, but then we would also have to introduce a new way of reporting unexpected calls on stubs. The verify part of `MockFactoryBase.verifyExpectations` looks like a good place to do so, but it's not so easy to change it without breaking *mocks*. 

Anyway, I'm going to create a fix for this bug in next 2 weeks. 

In meantime, I recommend you to use mocks instead of stubs for such situations (i.e. `inSequence` + nontrivial logic describing what to return). 

And to be honest, I generally prefer mocks to stubs:
- I don't like to repeat myself (in case of stubs I often have to declare what to return, and then verify that everything was called in a correct manner)
- mocks are more precise (there are no default values, nor implicit `anyNumberOfTimes`) 
- I find it easier to read test cases when mocks are described at the beginning of test

So I use stubs only to stub simple and unimportant components, and mocks to mock the important/complex part.

**Comment by gzm0** [comment]
> And to be honest, I generally prefer mocks to stubs:

I agree with you to some extent. The precise problem I am facing here, is that my unit creates identifiers internally and I need to verify them on the calls it does to create it:

```scala
val objUnderTest = ???

val id = objUnderTest.create()
objUnderTest.delete(id)
```

I want to verify that the calls `objectUnderTest` performs to setup internal stuff have the right `id` associated to them. To be able to do this with mock-style, I need to create something like mockitos ArgumentCaptor. In stub style, I can just use `id` as defined above.

**Comment by barkhorn** [comment]
I would refactor the mock based test to this to cover the case for dynamic values (here faked by incrementing `id`):

```scala
val comp = mock[Comp]

var id = 7
var idsGenerated = 0
def getId = {
  val current_id = id
  id += 42
  idsGenerated += 1
  current_id
}

comp.create _ expects() onCall { () =>
  val id = getId
  comp.destroy _ expects id once()
  id
} twice()

methodUnderTest(comp)

idsGenerated should be (2)
```

So the expectation on `destroy` for a certain id would only exist after `create` was called, as the `onCall` handler registers it

The output of the stub verification looks a bit misleading in this case, but I think this is an effect of the allowed calls being registered first, and the verifications actually demanding a different order later on.
The test design is complicated to follow
So I am closing this, pending stronger evidence for investigation.

**Comment by gzm0** [comment]
I agree that your solution is cleaner to the testing problem at hand. However, there is still an issue with the match report: IMO it should not contain "create() any number of times (called twice)".

Also I'm not sure I understand what you mean with " effect of the allowed calls being registered first, and the verifications actually demanding a different order later on.". Isn't this what stub-style is supposed to be?

**Comment by barkhorn** [comment]
Oh, great that you responded.

In this test, both expectation 1 and expectation 2 have the same signature (create without args), so the call looks identical. The CallHandler for expectation 1 eats up both calls and counts it, but I don't see it as a bug either as that is quite valid to do - how should the handler know there is a second expectation which also satisfies this call?
Note, a stub has an implied call count of [0..infinite].

Mocks behave differently as they have a call count of 1 in this case, so the first handler rejects the 2nd `create` call, letting the 2nd handler verify it.

So I think the difference in behaviour may look unexpected at first, but is down to the semantincs of mock vs stub.

Hope that makes it clearer.
