### ISSUE TITLE
Scala 2.10 support for 3.2.2

### ISSUE THREAD

**Issue by AlexeyRaga** [paulbutcher/ScalaMock#108]
Is it possible to have Scala 2.10 version on maven central?

**Comment by paulbutcher** [comment]
I'm afraid that ScalaMock 3 doesn't compile against Scala 2.10 at the moment. It might be possible to get it to compile with Macro Paradise, but it's not something I've tried.

If this is something you fancy looking at, I'd be very happy to accept a pull request.

**Comment by pawel-wiejacha** [comment]
I think ScalaMock-3.2.2 should work with Scala 2.10 - branch `master-2.10` already contains backported ScalaMock-3.2.1.

**Comment by pawel-wiejacha** [comment]
Travis build passed - https://travis-ci.org/paulbutcher/ScalaMock/builds/62275035 and ScalaMock-3.2.2 for Scala-2.10 was released. It should be visible on maven central in next 2 hours.

**Comment by AlexeyRaga** [comment]
Thank you very much!

**Comment by paulbutcher** [comment]
D'oh! Sorry guys, I completely forgot about this. Thanks for being more on the ball than I am.
