### ISSUE TITLE
Issue with mocking Trait

### ISSUE THREAD

**Issue by santoshv98** [paulbutcher/ScalaMock#109]
I have the following trait as part of my Play Application and the corresponding ScalaTest:

```java
trait MyProcess[A] {
  type B
  type C
  type D
  def stage1(s: String): B
  def stage2(b: B)(implicit e: ExecutionContext, app: Application, a: A): Future[C]
  def stage3(c: C)(implicit e: ExecutionContext, app: Application, a: A): Future[JsResult[D]]
  def process(s: String)(implicit e: ExecutionContext, app: Application, a: A): Future[JsResult[D]] = {
    val b = stage1(s)
    val f_d = for {
      c <- stage2(b)
      d <- stage3(c)
    } yield d
    f_d
  }
}

class TestController extends PlaySpec with Results with MockFactory {
  "MyController" must {
    " testing for method process" in {
      running(FakeApplication()) {

        implicit val context = scala.concurrent.ExecutionContext.Implicits.global
        implicit val s = "implicit String"
        implicit val currentApp = play.api.Play.current

case class TestParms(s: String)
abstract class TestProcessor extends MyProcess[TestParms] {
          type B = String
          type C = String
          type D = String
        }

        implicit val t = stub[TestProcessor]
        t.stage1(_: String).when(token).returns(testToken)

        (t.stage2(_: String)(_: ExecutionContext, _: Application, _: TestParms)).when(token, context, currentApp, tp).returns({
          Future.successful(stage2String)
        })
        (t.stage3(_: String)(_: ExecutionContext, _: Application, _: TestParms)).when(token, context, currentApp, tp).returns({
          Future.successful(Json.fromJson[String](Json.parse(stage3String)))
        })
}
}
}
}
```
My expectation is to set this stub into another scala class and test the overall process flow. When I attempt to mock the stage1 method this way, the compiler gives the following error:

```scala
overloaded method value when with alternatives:   (resultOfAfterWordApplication: org.scalatest.words.ResultOfAfterWordApplication)Unit <and>   (f: => Unit)Unit  cannot be applied to (String)	TestFBController.scala	/play-scala/test/controllers
```

Why am I not able to stub the first method when I am able to stub the rest of the 2 by just following the syntax of the method?

**Comment by paulbutcher** [comment]
Forgive me, @santoshv98, but I'm confused. The error that you're getting is from ScalaTest, not ScalaMock. It appears to suggest that something about the structure of how you're using `PlaySpec` (which I assume derives from ScalaTests's `WordSpec`?) is incorrect. I can't see anything relating to your mock or the `stage1` method in the error?

Perhaps you could cut this down to a minimal example so we can see the wood for the trees and resubmit if you're still experiencing an error?

**Comment by santoshv98** [comment]
Yes, I pulled this outside the playspec into a flatspec and it worked. 

````t.stage1(_: String).when(token).returns(testToken)````

I will post the code and let you know so that you can see whats happening.
