### ISSUE TITLE
curry confusion

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#110]
The docs http://scalamock.org/api/index.html#org.scalamock.package don't have an example of how to mock a function with multiple parameters and an implicit curry, so I'm trying to extrapolate what to do.

I'm trying to mock out the spray-cache https://github.com/spray/spray/blob/master/spray-caching/src/main/scala/spray/caching/Cache.scala#L52 like this

``` scala
 val cache = mock[Cache[Set[String]]]

(cache.apply(_: Any, _: () => Future[Set[String]])(_: ExecutionContext)).expects(*, *, *).returning(Future.successful(keys))
```

but that is giving me

```
value expects is not a member of (Any, () => scala.concurrent.Future[Set[String]], scala.concurrent.ExecutionContext) => scala.concurrent.Future[Set[String]]
[error]       (cache.apply(_: Any, _: () => Future[Set[String]])(_: ExecutionContext)).expects(*, *, *).returning(Future.successful(keys))
```

this is pretty messy syntax, but I can't see where I'm going wrong. Is this something wrong on my side or is it (unlikely) a bug?

**Comment by pawel-wiejacha** [comment]
Does this [answer](http://scalamock.org/user-guide/advanced_topics/#example-4---methods-with-implicit-parameters) solve your problem?

**Comment by fommil** [comment]
No, as far as I can tell I'm doing exactly what is expected

**Comment by fommil** [comment]
I give up, mocking out this `Cache` seems to be pretty impossible as it seems to be hitting all manner of corner cases in scalamock :disappointed:

**Comment by paulbutcher** [comment]
Yes, as far as I can tell, it does look like you're doing exactly the right thing. I briefly thought that the problem might be that you're trying to mock an `apply` method, but I've done some quick tests and that's not it.

So it's something about the specifics of Spray's `Cache` class, but it'll take more investigation to determine what I'm afraid.

**Comment by barkhorn** [comment]
Hi @fommil , still pursuing this one?

**Comment by fommil** [comment]
Nope
