### ISSUE TITLE
How to use scala mock to provide an alternative implementation of a class as stub for test?

### ISSUE THREAD

**Issue by Maatary** [paulbutcher/ScalaMock#111]
I found in a project i'm about to contribute with some external lib, that for testing purpose they set up a mock database manager. However what this database manager does, is creating an in-memory database and working with it. This is for testing purpose.

The framework used is Jmockit.

I try to find out how i could reproduce that in scalamock, but could not figure out.

Here how this is set up in jmockit:

/**
 * Mocks a DatabaseManager so unit tests can be run without a real DB connection
 * The code is basically the same as the original DatabaseManager but it
 * establishes a connection to an in-memory database.
 *
 * @author pvillega
 */
@MockClass(realClass = DatabaseManager.class)
public class MockDatabaseManager {...}
Is there anything that could support that in scalamock. I know this is related to how the all application has been developed. Especially how they used or did not used dependency injection. But nevertheless we have to deal with legacy code sometime :) (most of the time)

The only thing i see is writing all the function of a stub. A - However that is just not nice. B - Also it is not a full class that can retain state. So everything would have to be manage in the enclosing class that is creating the stub. c - Again, legacy code do a lot of funny things inside the class, so i would have to recreate all the code and etc... d - I would appreciate to reuse what they MockDatabaseManager.

Any advise?

**Comment by paulbutcher** [comment]
It sounds to me as though what you're after is just a perfectly normal class. ScalaMock exists to make creating mocks that return "canned" values as easy as possible. If I understand you correctly, you actually want a class with non-trivial behaviour (it actually implements a database, just one that resides in memory)? I'm not sure what value ScalaMock brings to this use case.

In fact, I'm not sure what value Jmockit brings in the original code you're trying to duplicate?

**Comment by Maatary** [comment]
What is happening here is that at runtime the DatabaseManager class is
replaced my the mock one. This is a perfect solution in this project
because of the way things has been coupled.

/**
 * Mocks a DatabaseManager so unit tests can be run without a real DB connection
 * The code is basically the same as the original DatabaseManager but it
 * establishes a connection to an in-memory database.
 *
 * @author pvillega
 */
@MockClass(realClass = DatabaseManager.class)
public class MockDatabaseManager
{.......}

**Comment by Maatary** [comment]
IT is not ideal but this is a legacy code

**Comment by paulbutcher** [comment]
Apologies, but I don't believe that ScalaMock can help you as things currently stand.
