### ISSUE TITLE
Unrecognised structure: Ident(TermName("parseSentenceFn")) on refactoring

### ISSUE THREAD

**Issue by janekdb** [paulbutcher/ScalaMock#113]
When making a change that should be a refactoring a compile error is encountered.

This compiles,

```
(xClient.parseSentence _).when(*).onCall { p: String => parser(p)}
```

This fails to compile,

```
val parseSentenceFn = xClient.parseSentence _
parseSentenceFn.when(*).onCall(parser)
```

```
ScalaMock: Unrecognised structure: Ident(TermName("parseSentenceFn"))
```

**Comment by pawel-wiejacha** [comment]
Thanks for the bug report.

It should be easy to fix.

**Comment by howyp** [comment]
This caught me too. We managed to work around it for the moment by forcing the implicit conversion to happen at the `val` declaration, something like:

```scala
val parseSentenceFn: StubFunction[_,_] = xClient.parseSentence _
parseSentenceFn.when(*).onCall(parser)
```

Hope that helps until the bug is fixed!

**Comment by janekdb** [comment]
:beer:
