### ISSUE TITLE
Parameterized fixture support/patterns?

### ISSUE THREAD

**Issue by jstultz** [paulbutcher/ScalaMock#116]
I've found the following rather helpful in thinking about how to share mocks and expectations between test cases:

http://www.scala-lang.org/api/current/index.html#scala.Product

However, something I've wanted to do in a few cases is have parameterized fixtures, where the expectations are still shared, but are based in each test on a parameter specific to that test. For example, I may have some set of different variants of a class that should be treated the same by the shared expectations/stubs, but may be treated differently and have different specific expectations added on in each individual test case.

However, this is tricky to do with the nature of trait inheritance.

This is a simplification of a first pass attempt:

``` scala
package test

import org.scalamock.scalatest.MockFactory
import org.scalatest.FunSpec

case class Foo(id: Int, value: String)

trait FooStore {
  def getFoo(id: Int): Foo
}

class TestSpec extends FunSpec with
  MockFactory {

  val fooStore = mock[FooStore]

  trait BaseFooTest {
    def foo: Foo

    (fooStore.getFoo _).expects(foo.id).returning(foo)
  }

  describe("apply") {
    it("gets the foo from the foostore") {
      new BaseFooTest {
        val foo = Foo(1, "foo")
        fooStore.getFoo(foo.id)
      }
    }
  }
}
```

This fails with an NPE:

```
[info] - gets the foo from the foostore *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at test.TestSpec$BaseFooTest$class.$init$(TestSpec.scala:20)
[info]   at test.TestSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anon$2.<init>(TestSpec.scala:25)
[info]   at test.TestSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(TestSpec.scala:25)
[info]   at test.TestSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestSpec.scala:25)
[info]   at test.TestSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestSpec.scala:25)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
```

Presumably because the expectation code is called in `BaseFooTest` constructor, before the test code constructor is run (and of course, the constructors must be executed in that order).

We can partially avoid the issue by using `onCall` rather than `returning`, so that the execution of that bit is deferred until the call is made:

``` scala
    (fooStore.getFoo _).expects(foo.id).onCall((_: Int) => foo)
```

This is not quite a complete solution, however, since there's still `foo.id`. This can be worked with `expects(*)`, either choosing not to care about the parameter value or performing a check in the function passed to `onCall`.
However, it would be much nicer if there were a way to similarly defer execution of the arguments passed to `expect` until later, to avoid the NPE (assuming I'm correct in thinking that's why it is occurring).

Are there other ways around this, or perhaps a different pattern I haven't thought of to support sharing parameterized expectations between tests?

**Comment by barkhorn** [comment]
foo.id was null in your example. If you change it as below, your suite runs ok:
```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.FunSpec

case class Foo(id: Int, value: String)

trait FooStore {
  def getFoo(id: Int): Foo
}

class FooTest extends FunSpec with MockFactory {

  val fooStore = mock[FooStore]

  trait BaseFooTest {
    def foo: Foo

    def setExpectations() = {
      (fooStore.getFoo _).expects(foo.id).returning(foo)
    }
  }

  describe("apply") {
    it("gets the foo from the foostore") {
      new BaseFooTest {
        val foo = Foo(1, "foo")
        setExpectations()
        fooStore.getFoo(foo.id)
      }
    }
  }
}
```
