### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by rozza** [paulbutcher/ScalaMock#119]
Both scalatest and specs2 now have a 2.12.0-M2 release.  

So I was hoping this could be added to the roadmap.

**Comment by chipsenkbeil** [comment]
:+1: on this. Want to add a Scala 2.12 build for https://github.com/chipsenkbeil/scala-debugger, but I'm using ScalaMock throughout my tests.

**Comment by chipsenkbeil** [comment]
@paulbutcher, with [Scala 2.12.0-M4](https://github.com/scala/scala/releases/tag/v2.12.0-M4) now out and boasting feature completeness, it looks like a lot of projects are adding a 2.12 build. Would it be possible to get a 2.12 build for ScalaMock? [Ensime Scala Debugger](https://github.com/ensime/scala-debugger) uses it for testing and won't be able to add a tested 2.12 build without it.

**Comment by paulbutcher** [comment]
Understood. I'm currently in China, on the wrong side of the Great Firewall, but will look at doing this when I'm back in the UK next week.

**Comment by chipsenkbeil** [comment]
@paulbutcher, any update for this?

**Comment by chipsenkbeil** [comment]
@paulbutcher,  still hoping for this to come to pass one day.

**Comment by daemas** [comment]
Is there any hope on getting this done any time soon?

**Comment by barkhorn** [comment]
raised a PR for this #155

**Comment by joshgarnett** [comment]
Any ETA on when #155 will be merged and pushed to maven?  Thanks!

**Comment by barkhorn** [comment]
this is now synced to JCenter. pushing to Sonatype/Central still has issues with some missing GPG signatures on v3.3.0.

**Comment by mdbergmann** [comment]
Greetings. How's the Maven Central push coming?

**Comment by barkhorn** [comment]
working on it. still need to manually upload a few missing files to bintray before sync will succeed

**Comment by fommil** [comment]
@barkhorn I find going via sonatype is far far easier, but the first time is a PITA.

**Comment by barkhorn** [comment]
@fommil that's probably true, but v3.3.0 was published without some gpg signatures, so i'd rather fix this than work around it. Otherwise the download would work for people using Central, but be incomplete for people using JCenter - like myself ;)

**Comment by barkhorn** [comment]
Sync with Sonatype OSS was a success now. 3.4.1 (built for Scala 2.11 and 2.12) should be appearing before the end of the day.

**Comment by fommil** [comment]
thank you!!!! can you please make a 2.10 release of the same number? (makes cross builds easier)

**Comment by barkhorn** [comment]
Agreed, that will be #157

**Comment by stela** [comment]
Works, could download 3.4.1 from central and finally migrate to scala 2.12 :+1:

**Comment by chipsenkbeil** [comment]
@barkhorn, you are my hero!
