### ISSUE TITLE
sbteclipse-plugin dependency is very old

### ISSUE THREAD

**Issue by SethTisue** [paulbutcher/ScalaMock#121]
I'd suggest either updating the dependency to 4.0.0 (current version recommended at https://github.com/typesafehub/sbteclipse as of 25-Oct-2015)...

...or removing it entirely, and just let people add the plugin in their global sbt settings if they are Eclipse users

**Comment by barkhorn** [comment]
agreed, this can be added via global plugins for people who prefer eclipse

**Comment by SethTisue** [comment]
fixed in c85dcc0cbfa2af53b6c78b0464c068e39c990282
