### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by pedrorijo91** [paulbutcher/ScalaMock#122]
The last commit is from 7 months ago. Is anyone thinking about keep supporting it?

**Comment by paulbutcher** [comment]
It's not dead, but it is in hibernation. Unfortunately, fundamental limitations in Scala's current macro support mean that it's not possible to fix many of the outstanding bugs in ScalaMock (trust me, I've tried—see the "objectmocks" and "scalamock4" branches for abortive attempts).

So I'm waiting for @xeno-by's scala.meta before tackling them again.

I'm happy to accept pull requests if there are particular issues that are causing problems in the meantime, but real fixes depend on scala.meta.

**Comment by pedrorijo91** [comment]
:+1:
