### ISSUE TITLE
Mocking/stubbing a typed method with different types doesn't register as different calls

### ISSUE THREAD

**Issue by eyalroth** [paulbutcher/ScalaMock#126]
Say I have a class with a typed method:

```
class Foo {
    def bar[T]() : T = ???
}
```

and I want to mock it for different types:

```
val foo = stub[Foo]
(foo.bar[Int] _).when().returns(1)
(foo.bar[String] _).when().returns("bla")
```

Now let's try and invoke the stub:

```
foo.bar[String]()
```

This will throw a casting exception, because the method will try to return `1` instead of `"bla"`!
The problem is not the casting exception, but the fact that the returned value is of the first `when`.
I would expect for each `when` to stub a different call to the method, just as if I would declare two `when`s on different parameters/arguments.

**Comment by bkowalik** [comment]
ScalaMock adds and resolves `mock` or `stub` call handlers at runtime so there is no information at runtime about type `T` and calls `foo.bar[String]()` `foo.bar[Int]()` are undistinguishable. My solution for that is as follows:
```scala
class Foo {
  def bar[T: ClassTag]() : T = ???
}

val foo = stub[Foo]
(foo.bar[Int]()(_: ClassTag[Int])).when(implicitly[ClassTag[Int]]).returns(1)
(foo.bar[String]()(_: ClassTag[String])).when(implicitly[ClassTag[String]]).returns("bla")

foo.bar[String]()
foo.bar[Int]()
```
So ScalaMock works but Scala has it's runtime type erasure which makes this calls undistinguishable.
thanks to that
