### ISSUE TITLE
Is ScalaMock broken?

### ISSUE THREAD

**Issue by marconilanna** [paulbutcher/ScalaMock#127]
Sorry, I really hope I'm doing something wrong or misunderstanding the issue here.

ScalaMock 3.2.2 with ScalaTest 2.2.5, Scala 2.11.7, and sbt 0.13.9.

```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.FreeSpec

class CrazySpec extends FreeSpec with MockFactory {
  "crazy" in {
    val crazy = stub[Crazy] // mock[Crazy] gives same results
    assert(crazy.toString === "crazy")
  }
}

class Crazy {
  override def toString = "crazy"

  private val s = "*" * 20
  println(s"$s just to show a point: $toString $s")
}
```

I would expect the test to fail with an NPE (since I didn't set expectations on the `toString` method) and the constructor **NOT** to be called. However this is the output when I run the tests:

```
[info] Compiling 1 Scala source to [...]
******************** just to show a point: crazy ********************
[info] CrazyTest:
[info] - crazy
[info] Run completed in 154 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 2 s, completed 8-Jan-2016 2:22:13 PM
```

How come the tests pass? Why did the constructor run?

**Comment by marconilanna** [comment]
I've created a minimal project to reproduce the issue: https://github.com/marconilanna/scalamock-issue

**Comment by paulbutcher** [comment]
This is ScalaMock's expected (although, as you correctly observe, undesirable) current behaviour. At present, mock objects are derived from the class they mock, and override all of its methods. As constructors cannot be overridden, the constructor is called.

This is one of the (many) things that's waiting for @xeno-by to finish scala.meta for a fix :-)

**Comment by marconilanna** [comment]
Hi @paulbutcher Thanks for the reply. But it only addresses half the issue:

> At present, mock objects are derived from the class they mock, and override all of its methods

That doesn't seem to happen, either. The `toString` method wasn't overridden, it was called as-is on the base class. The same happens with `val`, they are not overridden. I'll open a separate issue for it.
