### ISSUE TITLE
Add Travis CI and extract ScalaMock as organization

### ISSUE THREAD

**Issue by bkowalik** [paulbutcher/ScalaMock#135]
I think that good move would be to extract ScalaMock to it's own open source organization and add TravisCI integration so that every PR would be build. This would enhance contribution feedback.

**Comment by paulbutcher** [comment]
There is already a Travis CI (there's a link at the top of the README):

https://travis-ci.org/paulbutcher/ScalaMock

As for creating a new open source organisation, I'm not opposed to this, but I'm not sure I see what value it would really add?

**Comment by bkowalik** [comment]
Sorry, didn't noticed TravisCI. If you consider organization it would be nice to aggregate all ScalaMock things under one namespace. What do you think?

**Comment by barkhorn** [comment]
agree that a github org would be useful, but the number of committers is not very high at the moment.
I created a scalamock org anyway, as a placeholder: https://github.com/scalamock
Maybe we can revisit possible repo shuffles later, I think atm it would just confuse things.
Further, there is another organization on bintray for releases: https://bintray.com/scalamock
And, ScalaMock is registered on Scaladex: https://scaladex.scala-lang.org/paulbutcher/scalamock
