### ISSUE TITLE
Mocking Java class which implements Interface

### ISSUE THREAD

**Issue by thrykol** [paulbutcher/ScalaMock#136]
I've come across an issue where I am trying to mock a 3rd party Java class which implements an interface but changes the return type of a method defined by the interface.

Given interface `A` which defines method `M` as returning an array of type interface `B`.
Given implementation `ImplA` which implements `A`
Given implementation `ImplB` which implements `B`
Given `ImplA` defines method `M` as returning an array of type `ImplB`
Then `mock[ImplA]` results in a compile error stating that method `M` has an incompatible type

The following is a simplified example of the Java code

```
public interface ContainerInterface
{
    public MemberInterface[] get();
}

public interface MemberInterface { }

public class Container implements ContainerInterface
{
    // The interface specifies the return type as MemberInterface[]
    public Member[] get()
    {
        return new Member[0];
    }
}

public class Member implements MemberInterface { }
```

mocking the `Container` class results in the compile time error

```
[error] MockSpec.scala:15 overriding method get in trait ContainerInterface of type ()Array[MemberInterface];
[error] method get has incompatible type
[error]     val myMock = mock[Container]
[error]
```

I am using `scalamock 2.11-3.2.2`.

**Comment by bkowalik** [comment]
In my opinion this is not a bug but incompatibility. Arrays in Scala are invariant and mock that is created by ScalaMock is presented below:
```scala
{
  final class $anon extends com.paulbutcher.test.Container {
    def <init>() = {
      super.<init>();
      ()
    };
    val mock$special$mockName = MockTest.this._factory.generateMockDefaultName("mock").name;
    override def get(): Array[com.paulbutcher.test.Member] = $anon.this.mock$get$0.apply();
    val mock$get$0: MockFunction0[Array[com.paulbutcher.test.Member]] = new MockFunction0[Array[com.paulbutcher.test.Member]](MockTest.this._factory, scala.Symbol.apply(scala.Predef.augmentString("<%s> %s%s.%s%s").format($anon.this.mock$special$mockName, "Container", "", "get", "")))
  };
  new $anon()
}.asInstanceOf[com.paulbutcher.test.Container]
```
ScalaMock uses Scala syntax to create mocks so it overrides `get` method signature with `Array[com.paulbutcher.test.Member]` what is illegal in Scala. For me it is not a bug. If you want to mock such signatures you have to use Java world mocking library. This is where compatibility between Scala and Java breaks.

**Comment by thrykol** [comment]
Not too strong in the variance concept yet, but that makes sense.  I'll look into an alternate solution.  Thanks.
