### ISSUE TITLE
Support partial stubbing

### ISSUE THREAD

**Issue by erdavila** [paulbutcher/ScalaMock#141]
Given the class:

``` scala
class Service {
  def getValue(): String = {
    // Do some processing
  }

  def process(): String = {
    val value = getValue()
    // Process `value` and generate the return value
  }
}
```

I would like to test `process()` avoiding the processing of `getValue()` in some way like this:

``` scala
val service = partialStub[Service]
(service.getValue _).when().returns("string")

val result = service.process()

assert(result == "a string result")
```

**Comment by bkowalik** [comment]
From what I know ScalaMock rips off (almost) every method so you cannot partially stub or mock.

**Comment by barkhorn** [comment]
I am not sure we should be supporting this pattern in ScalaMock.
There are ways to inject factories or functions in scala code that would make the code above more testable.
E.g. a simple suggestion would be:
```scala
  def getValue(): String = ???
  def process(value: () => String = getValue): Unit = {
    val x = value()
  }
```
