### ISSUE TITLE
Mocks/Stubs returning Futures not working

### ISSUE THREAD

**Issue by vicaba** [paulbutcher/ScalaMock#143]
After writing some tests mocking methods that return a Future and getting them failed for no apparent reason, I've made a MWE to see if the problem are my tests or the Futures that methods/tested classes return. Surprisingly, the tests without classes returning Futures pass. If I change them to return Futures, they sometimes pass and sometimes don't. Why is this undeterministic behaviour happening? I've made the code available via a Github repo in: https://github.com/vicaba/scalatestNotWorking/tree/master. There are thwo branches, "master" where methods return a Future[T] and fail, and "withNoFutures" where methods return just a T and they don't fail. Also, it is important to highlight that with Futures, the first test usually passes but the second one don't. Can anyone explain me what's happening? I've posted a question on stackoverflow too: http://stackoverflow.com/questions/38076264/scalatest-and-scalamock-tests-not-passing-when-futures-are-involved .

**Comment by barkhorn** [comment]
Tried to access your code but it seems to have been removed
