### ISSUE TITLE
develop version based on scala.meta

### ISSUE THREAD

**Issue by cleverdeveloper** [paulbutcher/ScalaMock#145]
It looks like scala.meta 1.0 is out, so the promise on a roadmap page might be out-of-date. Do I understand correctly the project still needs new macros to be released?

**Comment by SrikanthTati** [comment]
I just hit a road block with not being able to mock a class with final member. It turns out, support for this was waiting on scala.meta. Any plans for this?

**Comment by cleverdeveloper** [comment]
You can have it already. There are several options.

One is to merge the following pull request yourself:
https://github.com/paulbutcher/ScalaMock/pull/132

Another is to build the following version which already includes the fix:
https://github.com/PagerDuty/ScalaMock

**Comment by barkhorn** [comment]
Scala.meta does not support Scala 2.10 at the moment. see https://github.com/scalameta/scalameta/issues/295

**Comment by barkhorn** [comment]
Also Scala.JS missing: https://github.com/scalameta/scalameta/issues/359

**Comment by barkhorn** [comment]
https://github.com/scalameta/scalameta/pull/761 has been merged now

**Comment by barkhorn** [comment]
Scalajs is supported now. No 2.10 support as of now, but considering to build ScalaMock 4.x without support for 2.10. So removing the blocker on this

**Comment by barkhorn** [comment]
Means we should do #187

**Comment by barkhorn** [comment]
See https://scalameta.org/

Exists for 2.11 and 2.12 so we'll need to temporarily drop 2.13 support in the new version

**Comment by barkhorn** [comment]
given that Scala is heading towards release 3.0 and has a different API again, I am not sure if this is worth investing time anymore. there are a number of open bugs that would benefit from a scala.meta implementation, but not sure how well, if at all, this could be reused when https://docs.scala-lang.org/scala3/guides/macros/index.html becomes stable

**Comment by barkhorn** [comment]
closing this as Scala 3 is out now
