### ISSUE TITLE
question about error not mentioned in documentation

### ISSUE THREAD

**Issue by london-coder** [paulbutcher/ScalaMock#146]
Hi, when using ProxyMockFactory to mock a trait, I get a compilation error:
<from inside IntelliJ 2016.2: using scala version 2.11.7, jvm version 1.8.0_91,>
I'm using Scalatest FlatSpec class in the test class not the FlatSpecLike trait.

Inside the IDE, no compilation error shows up, but when the maven compile runs, it emits the following:

Error: could not find implicit value for parameter mockContext: org.scalamock.context.MockContext
    val m = mock[TransactionProcessor]

I could not see anything in the docs on the web site about implicit MockContext. Can anyone tell me how to fix the error I'm seeing?

Many thanks.

**Comment by bkowalik** [comment]
I think that you should read this [http://scalamock.org/user-guide/sharing-scalatest/](http://scalamock.org/user-guide/sharing-scalatest/)

**Comment by london-coder** [comment]
Thanks for the reply, but I don't think it addresses the question. Where in the document link you refer to, is the implicit mock context to be found. I have, in fact, tried the style of solution referred to in to web site document, but the compilation error remains present and therefore the test cannot run.

**Comment by bkowalik** [comment]
You should construct your suite the other way. Your test should look like that:
`class MyTest extends FlatSpec with MockFactory`. Maybe my way is not correct somehow but I have never used `ProxyMockFactory` directly. Nevertheless, try with what I proposed you and let me know if it works.

**Comment by london-coder** [comment]
Hi Bartek
Thanks again for taking the time to reply.
I am trying to test functions in a trait, and mocks from MockFactory will not compile with traits. The scalamock documents indicate that when testing traits, the proxyMockFactory mock is the correct one to use. So, when I try the "ordinary" mock, there is a compiler error immediately visible when providing a trait name in the mock parameter. Thus, I have the problem described, the mock from ProxyMockFactory depends on an implicit mockContext that is not visible / reachable.

**Comment by london-coder** [comment]
Hi, 
In addition, I've tried explicitly creating a MockContext and that too, results in compilation errors; e.g.

Error: trait MockContext in package context cannot be accessed in package org.scalamock.context

    implicit val mockCtx = new MockContext {
      override protected def newExpectationException(message: String, methodName: Option[Symbol]): this.type = ???

      override type ExpectationException = this.type
    } 

Error: not found: type MockContext
    implicit val mockCtx = new MockContext { 


It looks like I'll have to give up on Scalamock, and try to find another (working) solution.


Thanks for your replies.

**Comment by barkhorn** [comment]
Not sure what to do with this, need a code snippet to reproduce or comment.
Please try with the latest version and raise a new issue if you still have a problem.

**Comment by lkemmerer** [comment]
I'm running into the same problem. This is a mostly whittled-down code sample that demonstrates the error:
```scala
trait SomeTrait {
  val hasThings = Vector("a", "b", "c")
  def doesStuff = println("hello")
}

class SomeClass {
  this: SomeTrait =>
}

class TestSpec extends ProxyMockFactory
  with FunSpecLike {

  val fakeTrait = mock[SomeTrait]
  val sut = new SomeClass with fakeTrait
}
```

Errors are:
```
Error:(34, 23) could not find implicit value for parameter mockContext: org.scalamock.context.MockContext
  val fakeTrait = mock[SomeTrait]
Error:(34, 23) not enough arguments for method mock: (implicit evidence$1: scala.reflect.ClassTag[com.shiftwise.rtisystem.test.actors.SomeTrait], implicit mockContext: org.scalamock.context.MockContext)com.shiftwise.rtisystem.test.actors.SomeTrait with org.scalamock.proxy.Mock.
Unspecified value parameter mockContext.
  val fakeTrait = mock[SomeTrait]
```

If I had to guess, I'd assume it has to do with the self-type annotation, but I'm new to Scala so I could be doing a number of other things wrong, too.

I'm using version 3.3.0 with Scalatest 3.0.0 with Scala version 2.11.8.

Thanks!

**Comment by barkhorn** [comment]
can you try again, with 3.4.2 please?

Also, I think you should be using org.scalamock.scalatest.proxy.MockFactory instead of ProxyMockFactory

**Comment by lkemmerer** [comment]
I've updated to 3.4.2 and my code now looks like:
```scala
trait SomeTrait {
  val hasThings = Vector("a", "b", "c")
  def doesStuff = println("hello")
}

class SomeClass {
  this: SomeTrait =>
}

class TestSpec extends org.scalamock.scalatest.proxy.MockFactory
  with FunSpecLike {

  val fakeTrait = mock[SomeTrait]
  val sut = new SomeClass with fakeTrait
}
```

and the errors have changes, but it's still not compiling:
```
Error:(34, 27) not found: type mock
  trait fakeTrait extends mock[SomeTrait]
Error:(35, 17) illegal inheritance;
 self-type SomeClass with TestSpec.this.fakeTrait does not conform to SomeClass's selftype SomeClass with .SomeTrait
  val sut = new SomeClass with fakeTrait
```

I realized this morning that the latter change was suggested above; sorry about that. I appreciate your patience and thank you for maintaining the project!

**Comment by barkhorn** [comment]
Hi, see my example below.
Not sure if you can SomeClass to SomeClass2 in your code, but I don't see a good way of mocking out the SomeClass version with the selftype, sorry.

```scala
import org.scalamock.scalatest.proxy.MockFactory
import org.scalatest.{FunSpec, FunSpecLike}

trait SomeTrait {
  val hasThings = Vector("a", "b", "c")
  def doesStuff() = println("hello")
}

class SomeClass {
  this: SomeTrait =>
}

trait SomeClass2 {
  val someTrait: SomeTrait
}

class Issue146Test extends FunSpec with MockFactory {
  describe("foo") {
    it("should work") {
      val fakeTrait = mock[SomeTrait]

      // does not compile
      //val sut = new SomeClass with fakeTrait

      val sut2 = new SomeClass2 {
        val someTrait = fakeTrait
      }
    }
  }
}
```

**Comment by lkemmerer** [comment]
Thank you for the example; while it's a little more complicated, it isn't tooo bad.  I think I've figured out how to rejigger my non-example code so that I can use the trait without selftyping and still test the functionality that uses the trait behavior, but if it doesn't work out, I'll try implementing the test based on your sample.

And that looks like a fantastic blog post. I appreciate your time and hope you have a good day! :)
