### ISSUE TITLE
Scalamock incompatible with ScalaTest 3.0.0-RC4

### ISSUE THREAD

**Issue by chauhraj** [paulbutcher/ScalaMock#147]
I am using **ScalaTest 3.0.0-RC4** along with **scalamock 3.2.2** and getting the following Compilation error.

`class MySpec needs to be a mixin, since method withFixture in trait AbstractMockFactory of type (test: MySpec.this.NoArgTest)org.scalatest.Outcome is marked `abstract' and `override', but no concrete implementation could be found in a base class
`

How can this be resolved?

**Comment by damirv** [comment]
I have just submitted a PR for scalatest 3.0.0: https://github.com/paulbutcher/ScalaMock/pull/149

**Comment by sarveshseri** [comment]
Is this still not fixed in 3.0.0 release ?

**Comment by bvenners** [comment]
This is an incompatibility of ScalaMock with ScalaTest 3.0. We fixed it in a version of ScalaMock that we released about a week ago: version 3.3.0 for Scala 2.11. Give that a try.

**Comment by sarveshseri** [comment]
Great. Nice work. 👍

**Comment by thejasbabu** [comment]
@bvenners Which version of ScalaTest and ScalaMock are compatible?

**Comment by zkendall** [comment]
I am getting this error with

  val scalaMockVersion = "4.4.0"
  val scalaTestVersion = "3.1.2"
