### ISSUE TITLE
Unable to mock val in a trait

### ISSUE THREAD

**Issue by madkinder** [paulbutcher/ScalaMock#148]
This issue is somewhat similar to #40, but not exactly the same.

Given the code:

``` scala
trait Animal {
  val species: String
}

val animal = stub[Animal]
(animal.species _).when().returning("dog")
```

I get the following:

```
Error:(146, 17) _ must follow method; cannot follow animal.species.type
      (animal.species _).when().returning("dog")
```

If I change `val` to `def` it compiles as expected.

---

I know that it is advised not to use `val`s in `trait`s since they cannot be implemented via `def`s. But that's exactly the intent: `species` is supposed to be a simple static value, and not being a result of a heavy computation.

Anyways, both `val`s and `def`s are implemented as Java methods, so I wonder, what gives?

---

Using Scala 2.11.8 and ScalaMock 3.2.2.

**Comment by barkhorn** [comment]
The way i see it, val gives you a guarantee of immutability, so not being able to override it seems correct.
I don't think it would be desirable to weaken that feature of Scala even if possible.
An option may be to subclass your trait and mock our anything that is not a value:

**Comment by madkinder** [comment]
> The way i see it, val gives you a guarantee of immutability, so not being able to override it seems correct.

Well, I wasn't talking about overriding, but about implementing. The `val` was declared within a `trait` and it had no implementation. So the idea was to require implementation in descendant classes.

**Comment by barkhorn** [comment]
```
trait Cat extends Animal {
  val species = "cat"
}
```
...then stub the cat?
But I guess it is the access to species you want to test specifically?

**Comment by madkinder** [comment]
Yes, exactly. The idea was to make sure that `species` value is read and used by the system under test.

**Comment by barkhorn** [comment]
i'll add this to the v4 milestone then, which should allow this sort of thing by using scala-meta

**Comment by barkhorn** [comment]
This is now mentioned as a known limitation in the FAQ: http://scalamock.org/user-guide/faq/

**Comment by barkhorn** [comment]
Let's track this under #40 , as these two issues are virtually identical (`class` vs `trait`)

You basically have two options:

- Use `def species: String` instead of `val`

- Design a negative test to, separately, check your code does indeed access the value:

```scala
  trait Animal {
    val species: String
  }

  class CodeUnderTest(animal: Animal) {
    def foo = s"I have a ${animal.species}"
  }

  "CodeUnderTest" should "access trait's val" in {
    class AnimalThatThrows extends Animal {
      override lazy val species: String = ???
    }

    val instance = new CodeUnderTest(new AnimalThatThrows)
    a[NotImplementedError] should be thrownBy instance.foo
  }
```
