### ISSUE TITLE
Is ScalaMock dead ?

### ISSUE THREAD

**Issue by dragisak** [paulbutcher/ScalaMock#153]
There hasn't been any changes in more than a year although people keep submitting pull requests.

**Comment by cleverdeveloper** [comment]
I would speculate the author is just a little bit busy until the end of the driving season: http://www.formulajedi.com/results

**Comment by endontoddy** [comment]
Can't tell if you're joking or not, but would be good to have some sort of update on if there are plans to continue support.

**Comment by cleverdeveloper** [comment]
The author did release the new version with ScalaTest 3.0 support couple of days ago, so it does seem he cares: http://search.maven.org/#search%7Cga%7C1%7Cscalamock

**Comment by dragisak** [comment]
Cool. I was worried because there was a big period of inactivity between April 2015 and August 2016.

**Comment by cleverdeveloper** [comment]
Well, according to these tickets it could also have been someone from @bvenners, @cheeseng, @gcberger and @pawel-wiejacha besides @paulbutcher. But, at least, we could say that _someone_ did the release.

https://issues.sonatype.org/browse/OSSRH-3573
https://issues.sonatype.org/browse/OSSRH-7916
https://issues.sonatype.org/browse/OSSRH-11141

**Comment by cleverdeveloper** [comment]
Epic win: http://www.formulajedi.com/news/185-wins-for-butcher-and-morgan-at-wet-donington
