### ISSUE TITLE
convert SBT build to .sbt format

### ISSUE THREAD

**Issue by barkhorn** [paulbutcher/ScalaMock#157]
- proper crossbuild for 2.11 and 2.12
- consider 2.10 compatibility (Spark users)
- remove deprecated inheritance from Build

**Comment by fommil** [comment]
Sbt is still on 2.10 making it the most popular version of scala :-)

**Comment by chipsenkbeil** [comment]
Scala debugger project could use a build that runs across 2.10, 2.11, and 2.12. Currently publishing against 2.10/2.11 and using ScalaMock in over 3000 unit tests; so, would be really nice to keep the same ScalaMock version across the board.

**Comment by barkhorn** [comment]
2.10 is back in the main trunk, you'll be happy to hear

**Comment by fommil** [comment]
Thank you!!

**Comment by barkhorn** [comment]
released to Central

**Comment by chipsenkbeil** [comment]
@barkhorn any way I can thank you for this? Donation? Something else?

**Comment by barkhorn** [comment]
Appreciate the thought and glad you like it.
But if you want to donate, rather consider https://www.cats.org.uk/donate/?b=1 or some other charity of your choice instead of me - they need it more :)
