### ISSUE TITLE
Adding scalamock dependency destroys any specs2 test suite

### ISSUE THREAD

**Issue by gnomff** [paulbutcher/ScalaMock#160]
Current dependencies:
```
testCompile "org.specs2:specs2-core_2.11:3.8.5"
testCompile "org.specs2:specs2-junit_2.11:3.8.5"
testCompile "org.specs2:specs2-mock_2.11:3.8.5"

testCompile "org.scalamock:scalamock-specs2-support_2.11:3.3.0"
```

Everything compiles until the scalamock dependency is added. Once it is added the project immediately stops compiling and all tests throw this error:
`
...in class CompileTest, multiple overloaded alternatives of method args define default arguments.
The members with defaults are defined in trait ArgumentsCreation in package mutable and trait ArgumentsArgs in package main.
`

Even very straightforward tests like this will no longer compile:
```
import org.specs2.mutable.Specification
import org.junit.runner.RunWith
import org.specs2.runner.JUnitRunner

@RunWith(classOf[JUnitRunner])
class CompileTest extends Specification {

  "my test should" >> {
    "compile" >> {
      ok
    }
   }
}
```

This makes scalamock unusable.

**Comment by barkhorn** [comment]
Hi @gnomff I see you used Scalamock 3.3.0 (linked against specs2 2.4.16).
Can you please try again, using 3.4.1? That links against a more recent version of specs2 and should work ok.

**Comment by gnomff** [comment]
Thanks for the quick reply! ScalaMock 3.4.1 depends on scala 2.12 (even though it is labeled 2.11!) which is why I downgraded to 3.3.0

**Comment by gnomff** [comment]
It looks like it's specifically scala-reflect:2.12.0 that it depends on

**Comment by barkhorn** [comment]
Oops.  That shouldnt be

**Comment by barkhorn** [comment]
confirmed this will be fixed in 3.4.2 once it's released (probably this weekend)

**Comment by gnomff** [comment]
Thank you!

**Comment by barkhorn** [comment]
3.4.2 released to Central

**Comment by gnomff** [comment]
Works perfectly!
