### ISSUE TITLE
Feature Request: Test mock expects/returning against the real object

### ISSUE THREAD

**Issue by mirosval** [paulbutcher/ScalaMock#166]
I would like to re-use the mocks I have defined to test the parameters/results against the object being mocked. This would be very useful when the implicit interface of the mocked object changes. In this case  the change is not detected at compile time, but the mock diverges from reality and I would like to know when that happens.

I see two ways of doing this:
1. Have some tool that can generate tests by looking at all the mocks defined in the code
2. Using some switch add a backing (real) object to the Mocked object, then ScalaMock would compare real results with the mocked ones and alert you when they diverge.

I am using ScalaMock to mock services which are slow/annoying to run fully, but I'm responsible for both sides of the interface. So 90% of the time I would run in the mock mode and only switch to real mode on CI or when there is a problem and this specific part of the interface needs to be tested.

I would be open to contributing this, but first I wanted to hear from somebody involved if this is possible or how it could be achieved.

**Comment by barkhorn** [comment]
That's an interesting idea.
Ideally, an API is stable enough that mocks don't break in the way you describe, but that is not always the case.
A way to run with either mocks or the production code would be to have a facade around the tests and run them parameterised?
E.g. in Scalatest, there is a mechanism to add a "tag" to a test, indicating it's a "slow test", for example: http://www.scalatest.org/user_guide/tagging_your_tests
You could use that and run the same action as with the mock tests, but only for some CI builds?

I am not sure if a verification layer of mock vs implementation is really a functionality that should be in the core framework, but as additional tooling around the library it might be a nice option.
Do you have an example piece of (pseudo-)code to share?

**Comment by mirosval** [comment]
I agree that the facade/switch idea is probably better. There are many problems with generating tests automatically.

I think the ScalaTest Tag approach could work. The way I imagine it would be something like this:

```
class Test extends FunSpec with Matchers {
  private val mock = TagBasedMockFacade(
    mock = mock[SomeClass], 
    real = new SomeClass()
  )
  
  describe("test") {
    it("should work with mocked") {
      // expects etc...
      mock.someFunction() // calls mocked
    }

    it("should work with mocked", ScalaMockFacadeUseReal) {
      // expects etc...
      mock.someFunction() // calls real
    }
  }
}
```

The point is that the `expects/returning` fails the test when there is a discrepancy between what the mock does and what the real object does.

This only really makes sense when calling the real object is impractical or slow. Otherwise you don't need mocks at all.

This way you'll have `Service A` and `Service B` that depends on `A`. `A` can have its own tests that ensure it is internally correct, same for `B`. `B` additionally mocks `A` in order to prevent having to depend on `A`. This approach would allow to use the same test that `B` uses internally against the real `A` validating that all the assumptions made on `Mock A` are valid.

**Comment by barkhorn** [comment]
In my projects, I use integration tests to act the wider interaction between frameworks and a particular module.
E.g.
- someProject
  - production sources
  - unit tests, using mocks where needed
- someProject-IT, dependsOn someProject
  - test code, using real APIs

However, the someProject-IT module only gets run on the CI server, and during normal development i do a someProject/test to only run the quick/cheap tests

**Comment by barkhorn** [comment]
i don't there is anything to do for this on the ScalaMock codebase, as discussed.
