### ISSUE TITLE
ScalaMock version on the quick-start page

### ISSUE THREAD

**Issue by pboschmann** [paulbutcher/ScalaMock#167]
Hi there.

I've just stumbled upon this mocking library and had to learn the hard way, that the version of ScalaMock with ScalaTest suppport specified on the [quick-start page](http://scalamock.org/quick-start/) (version 3.2.2 atm) doesn't play well with ScalaTest version I'm currently using (3.0.1)
According to PR #149 and #147 the ScalaMock version for ScalaTest 3.0 should be 3.3.0
Actually I've found out, that ScalaMock 3.4.1 seems also to work, but my testbase is quite small (using ScalaMock it for an hour or so… so I'm quite unsure about it).

Could you bump the version for ScalaMock on the quick-start guide?
And last, but not least: thank you for your work - it's a pleasure to work with ScalaMock so far and the color palette on the official site is calming and comforting. :)

**Comment by barkhorn** [comment]
you raise a valid point. The documentation needs updating in a few places.
Version 3.4.2 is current, so maybe use that for now. 3.5.0 will follow in a few weeks with some new features.

**Comment by pboschmann** [comment]
Thank you for your prompt answer.
Let me know if there are many places affected and you wish support in some way — originally I intended to submit a PR with the version bump, but could not find the source for the official page.

**Comment by barkhorn** [comment]
The documentation is currently on a separate branch.
For the next release, I think we should pull that into master so it's co-versioned with the source.
If you want to help out right now, you could fork and work with the gh-pages branch, and submit a PR.
However, static html pages are generated outside of the usual github mechanism, so there's two versions of each doc file right now.
