### ISSUE TITLE
Investigate macro compilation slowness [mockMethod perf bottleneck]

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#169]
I did a YourKit object allocation profile of our ensime/scala-debugger `test:compile` (which takes a lot longer than you'd expect) and found a few bottlenecks. `MockMaker.mockMethod` showed up as a culprit

https://github.com/paulbutcher/ScalaMock/blob/master/core/shared/src/main/scala/org/scalamock/clazz/MockMaker.scala#L201

and it might be the case that the `:+` creation of the list is very inefficient and ends up churning through memory.

I'll see about monkey patching locally with alternatives...

**Comment by fommil** [comment]
hmm, which binary does `MockAdapter.class` end up in? It's in the `shared` folder of `core` but it never gets published.

**Comment by fommil** [comment]
nvm: `scalamock-core-jvm`

**Comment by fommil** [comment]
after further investigation, I think just generally scalamock slows down the compile and this is a result of macros just being slow.

**Comment by fommil** [comment]
I think the problem has always been there, I don't think it's an easy fix: just one of those trade-offs developers must make.

**Comment by barkhorn** [comment]
for me to reproduce this and understand where the CPU cycles go, could you explain briefly how you looked at this? e.g. "cold start of sbt on commandline, attach profiler, run 'test'"? I only haveVisualVM here, but maybe that shows something similar.

**Comment by fommil** [comment]
If you can get hold of a gratis yoirkit license (they will give you one if you ask for scalamock) then you could try lions-share. Memory allocation counting is far more reliable than cpu when it comes to Scala code.

**Comment by barkhorn** [comment]
I've been playing with the profiler recently, but all hotspot it showed me are within SBT's codebase. Very interesting information though, nice tool.
1. start sbt
2. clean
3. compile
4. start a CPU sampling profile run
5. test:compile
6. end profile

Looking at the output of that snapshot more closely, it also highlights that macros invalidate some of SBT's internal dependency (classes) caching. That probably contributes to the slowdown.

If this is a big problem for you, then maybe look at ScalaMocks ProxyMocks, which don't use macros, or, as you commented in https://github.com/ensime/scala-debugger/issues/306 design immutable functional code that avoids the needs for mocks.
Personally I find I tend use mocks in places where my code intersects with OO patterns outside my control.

@fommil - happy if we close this or feel I should be looking at something particular bottleneck in ScalaMock's code?

**Comment by fommil** [comment]
I think the fix needs to be in macro paradise.... or parallel compile (triplequote)
