### ISSUE TITLE
Compiler error when using proxy.MockFactory and passing arguments

### ISSUE THREAD

**Issue by mkalish** [paulbutcher/ScalaMock#173]
Scalamock: 3.4.2
Scalatest: 3.0.1

When passing arguments to an expect there is several compile errors:
```
Error:(56, 87) type mismatch;
 found   : Long(0L)
 required: org.scalamock.matchers.MockParameter[Any]
    usageMock.expects('createUsage)(assessment, question, "questions", EmptyEdgeData, 0L).returning(Success(mockUsage))
```

Usage:
```
trait MyService {
    def testService(id: Long, count: Long, page: Long): Boolean
}

class MyTest extends FlatSpec with MockFactory {
    val mockService = mock[MyService]
    mockService.expects('testService)(0L, 0L).returning(false) // Error here
}
```

Not sure if I have configuration or I misusing it but this seemed to be how the example had it setup.

**Comment by barkhorn** [comment]
Hi,

your syntax isn't quite right, and your mock expectation is missing the third parameter to testService().

This will work - assuming you want to allow any number as the third param:
`mockService.testService _ expects(0L, 0L, *) returning false`

There are some examples at http://scalamock.org/user-guide/mocking_style/#mocking-objects

**Comment by barkhorn** [comment]
hi @mkalish did that answer your question?

**Comment by mkalish** [comment]
Thanks @barkhorn, I think I ended up confusing myself when reading the scalatest reference for scala mock: http://www.scalatest.org/user_guide/testing_with_mock_objects#scalamock

The other half of my issue was trying to do using the mocking with an object

`
object TestImplicits extends MockFactory {
    implicit val mockTestService: TestService = mock[TestService]
}
`

I'll go ahead and close this, since neither of my issues were a scalamock problem.

Thanks for the quick response though!
