### ISSUE TITLE
Adding ScalaMock dependency causes "not a member of package org.scalatest" error

### ISSUE THREAD

**Issue by fbertsch** [paulbutcher/ScalaMock#177]
I've added the library dependency for Scala Mock:
```
libraryDependencies += "org.scalamock" %% "scalamock-scalatest-support" % "3.4.2",
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.4"
```

And when I do, I get the following error:
```
CrossSectionalViewTest.scala:7: object TestFailedException is not a member of package org.scalatest
```
Which is obviously trying to use `org.scalatest.TestFailedException`.

The error goes away when I remove the scalamock dependency.

**Comment by barkhorn** [comment]
Using Scalatest 2.2 is not supported anymore.
Your dependency list overrides ScalaMock's dependency on Scalatest 3+ so it fails.
Please upgrade to a newer Scalatest, or let ScalaMock pull the correct version in transitively :)
(Or, if you really have to stick with Scalatest 2.x, downgrade ScalaMock to 3.2.2)

**Comment by fbertsch** [comment]
Ah, perfect - thanks!
