### ISSUE TITLE
Cannot access docs

### ISSUE THREAD

**Issue by hwroblewski** [paulbutcher/ScalaMock#181]
*If you want to discuss a new feature, please ignore/clear this form.*

### Please describe the expected behavior of the issue
I can read the scaladocs

### Please provide a description of what actually happens
I get an AccessDenied message:
```AccessDeniedAccess DeniedE68B270552422E0AyCvZ3E+OV89ihBK0JzWiC5AWLEjMwNf8hrUCxp6p38MSH0eyjEVkBwx5nTdDcSR5CAY725vlOlI=```

### Reproducible Test Case
Go to this link: https://www.javadoc.io/doc/org.scalamock/scalamock_2.11/3.5.0

**Comment by barkhorn** [comment]
thanks, you are right. older versions seem to work, or choosing scalamock-core. Looks like an empty jar was generated for the docs.

**Comment by barkhorn** [comment]
changed the links to refer to the correct artefact
