### ISSUE TITLE
ScalaMock not compatible with AsyncFlatSpec

### ISSUE THREAD

**Issue by jrobison153** [paulbutcher/ScalaMock#183]
Hi, 

I'm seeing an issue when trying to use ScalaMock in an asynchronous Scala test. 

### ScalaMock Version (e.g. 3.5.0)
3.5.0

### Scala Version (e.g. 2.12)
2.11

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
Should be able to verify stubs during an asynchronous test

### Please provide a description of what actually happens
Compile error on return type of test case

```
Error:(80, 48) type mismatch;
 found   : org.scalamock.handlers.CallHandler0[scala.concurrent.Future[String]] with org.scalamock.handlers.Verify
 required: scala.concurrent.Future[org.scalatest.compatible.Assertion]
      (futureFunStub.doSomeLongRunningThing _).verify
```

### Reproducible Test Case

```scala

import org.scalamock.scalatest.{AsyncMockFactory, MockFactory}
import org.scalatest.{AsyncFlatSpec, FlatSpec, Matchers}

import scala.concurrent.{ExecutionContext, Future}

class FutureTest extends AsyncFlatSpec
  with Matchers
  with AsyncMockFactory {

  var simpleFuture: Future[String] = _
  var futureFunStub: FutureFun = _

  def prepareForTest(): Future[String] = {

    simpleFuture = Future {

      val aString = "foo"

      aString
    }

    futureFunStub = stub[FutureFun]

    (futureFunStub.doSomeLongRunningThing _).when().returns(simpleFuture)

    futureFunStub.doSomeLongRunningThing()
  }

  behavior of "a ScalaMock stub in an asynchronous test"

  it should "be verifiable" in {

    prepareForTest

    // Compile error manifests on this line as this does not resolve to Future[Assertion]
    (futureFunStub.doSomeLongRunningThing _).verify
  }
}


class RegularTest extends FlatSpec
  with MockFactory {

  var futureFunStub: FutureFun = _

  def prepareForTest(): String = {

    futureFunStub = stub[FutureFun]

    (futureFunStub.doSomeQuickThing _).when().returns("yello")

    futureFunStub.doSomeQuickThing

  }

  behavior of "a ScalaMock stub in a synchronous test"

  it should "be verifiable" in {

    prepareForTest()

    (futureFunStub.doSomeQuickThing _).verify
  }
}

class FutureFun {

  implicit val ec = ExecutionContext.global

  def doSomeLongRunningThing(): Future[String] = {

    Future {

      "foo"
    }
  }

  def doSomeQuickThing(): String = {

    "bar"
  }
}

```

**Comment by barkhorn** [comment]
This is not an issue with ScalaMock.
Please read ScalaTest's documentation on async testing: http://www.scalatest.org/user_guide/async_testing
A test case body must have a return type of Future[Assertion] (async) or Assertion (sync cases).

So a quick fix for you might be to block on your future and then verify, using a for expression:
```scala
  it should "be verifiable" in {
    for (_ <- prepareForTest()) yield {
      (futureFunStub.doSomeLongRunningThing _).verify()
      succeed
    }
  }
```

But be careful with the way you set up the fixture. Your mocks are stored in mutable fields, so you may struggle to reuse them in other test cases with this pattern, especially when your async operations start overlapping. There is some guidance in our documentation how to safely share mocks: http://scalamock.org/user-guide/sharing-scalatest/
Personally, i get along well with the usage described in "Fixture contexts".

Hope that helped!

**Comment by jrobison153** [comment]
@barkhorn, thanks for the quick response; synchronizing on future using yield should get the job done.

**Comment by jrobison153** [comment]
@barkhorn Small update on this. I was able to get this working using Future.map per the ScalaTest guide which allows me to avoid blocking on the thread. It's a little strange that the test always returns 'succeed' but it will indeed fail correctly if the mock fails to 'verify'.

```

 it should "be able to verify stub" in {

    prepareForTest()

    simpleFuture map { aString => (futureFunStub.doSomeLongRunningThing _).verify }

    succeed
  }
```

**Comment by barkhorn** [comment]
in that case, you should probably put the succeed call inside the map function so the test case is fully async.
otherwise succeed may be evaluated first and scalatest counts the test as succeeded even when the future.map fails later? not sure, but could be a race condition hiding there

**Comment by jrobison153** [comment]
You are correct, ran into that yesterday. Will update.
