### ISSUE TITLE
Difference between MockFunction2-2 and MockFunction2-1

### ISSUE THREAD

**Issue by joshg-rms** [paulbutcher/ScalaMock#194]
What's the difference between `MockFunction2-1` and `MockFunction2-2` ?

```scala
def f(fn: (String, Int) => Int) = fn("hi", 5)
def fn = mockFunction[String, Int, Int]

fn.expects("hi", 5).returning(10)
f(fn) should be(10)
```
results in 
```
[info]   Unexpected call: MockFunction2-2(hi, 5)
[info]
[info]   Expected:
[info]   inAnyOrder {
[info]     MockFunction2-1(hi, 5) once (never called - UNSATISFIED)
[info]   }
[info]
[info]   Actual:
[info]     MockFunction2-2(hi, 5) (Option.scala:121)
[info]   org.scalatest.exceptions.TestFailedException:
```

Scala 2.12 and Scalamock 3.5.0

**Comment by barkhorn** [comment]
`def fn = ...` will create a new mockFunction each time it is called.
That is reflected in the names, which is why you see an expectation on ...-1 but a call on ...-2

if you change your code to use `val fn = mockFunction[String, Int, Int]` then everything should work as expected.

**Comment by joshg-rms** [comment]
Great, that makes sense, thanks
