### ISSUE TITLE
Unexpected call on productIterator() when printing mocked case class

### ISSUE THREAD

**Issue by thrykol** [paulbutcher/ScalaMock#199]
### ScalaMock Version
3.5.0

### Scala Version
2.11

### Runtime 
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)

### Please describe the expected behavior of the issue
Printing a mocked `case class` should not result in any expectation being triggered.

### Please provide a description of what actually happens
```
[info]   Unexpected call: <mock-1> MockIt.productIterator()
[info]   
[info]   Expected:
[info]   inAnyOrder {
[info]   
[info]   }
[info]   
[info]   Actual:
[info]     <mock-1> MockIt.productIterator() (Option.scala:121)
```

### Reproducible Test Case

```scala

import org.scalamock.scalatest.MockFactory
import org.scalatest.Matchers
import org.scalatest.WordSpec

class WidgetSpec extends WordSpec {

  "print name" in new MockFactory with Matchers {

    case class Widget(val a: String, val b: String)

    val widget = {
      class MockIt extends Widget("a", "b")
      mock[MockIt]
    }
    println(s"Widget:  ${widget}")
  }
}
```

**Comment by barkhorn** [comment]
Printing a class will call `toString` on that class. toString cannot be overridden by ScalaMock - it will use the original implementation - so there is no bug here.
If we would attempt to override toString, we could easily get infinite recursion, so this behaviour needs to stay as it is.
Suggest you print individual fields (e.g. `widget.a` instead) to avoid this.
