### ISSUE TITLE
Feature request: verifyZeroInteractions

### ISSUE THREAD

**Issue by bbarker** [paulbutcher/ScalaMock#204]
A call in mockito might look like:  `verifyZeroInteractions(factory)`; in ScalaMock, I guess it might look something like: `(factory _).verify().never()` or maybe more simple and sensible to maintain the mockito style API. Some interesting discussion at: https://github.com/mockito/mockito/issues/989

**Comment by barkhorn** [comment]
Hi, you already get a choice in mocking style: http://scalamock.org/user-guide/mocking_style/
If you want a mock with 0 interactions, you can just use a `mock[Thing]` and not declare any expected calls.

**Comment by bbarker** [comment]
I see how that makes sense now that you mention it - I was using the other style, coming from mockito.
