### ISSUE TITLE
Expectation not properly evaluated in Async context

### ISSUE THREAD

**Issue by tfayruzov** [paulbutcher/ScalaMock#213]
### Expected behavior
Test should fail because the mocked function is called only once, while expectation is set to have it called twice.

### Actual behavior
Test passes.

### Reproducible Test Case

```scala
import org.scalamock.scalatest.{AsyncMockFactory, MockFactory}
import org.scalatest.{AsyncFunSpec, Matchers}

import scala.concurrent.{ExecutionContext, Future}

class AsyncTestRepro extends AsyncFunSpec with Matchers with AsyncMockFactory {

  it("supposed to fail") {
    val mockClient = new MockClient

    val logic = new AsyncLogic(mockClient)

    // mockClient.mockExecute.expects(*, *).returns(Future.successful(1)).never - fails as expected
    // mockClient.mockExecute.expects(*, *).returns(Future.successful(1)).once - succeeds as expected
    mockClient.mockExecute
      .expects(*, *)
      .returns(Future.successful(1))
      .twice // succeeds, although not expected

    logic.run(1).map(_ should equal(1))
  }
}

trait Client {
  def execute(i: Int)(implicit ec: ExecutionContext): Future[Int]
}

// This mock is shared across multiple tests and the `mockExecute` behavior defined in each test.
class MockClient extends Client with MockFactory {
  val mockExecute = mockFunction[Int, ExecutionContext, Future[Int]]("mockedFunction")
  override def execute(i: Int)(implicit ec: ExecutionContext) =
    mockExecute(i, ec)
}

class AsyncLogic(client: Client) {
  def run(i: Int)(implicit ec: ExecutionContext): Future[Int] = client.execute(i)
}
```
I'm suspecting it may have something to do with (non-async) `MockFactory` used to build MockClient, but I was not able to make it work with `AsyncMockFactory`, because it fails with `Null expectation context` error at runtime.

**Comment by barkhorn** [comment]
The problem is that you have two different MockFactories.
The mock is created in a factory inside your MockClient, so the verification never runs and the two scenarios where you have set up a call pass.
The MockFactory only verifies ScalaTest (or specs2) test cases, so the AsyncMockFactory (which has no mocks set up) has nothing to verify at the end of your test.
I suggest setting up the mockFunction in your test suite, then injecting it into the MockClient as a constructor parameter.

I also note your comment about "this mock is shared". Be careful with that. Because of the automatic verification, the expectation context is reset after each executed test. Acceptable sharing patterns are documented on the website: http://scalamock.org/user-guide/sharing-scalatest/

Some more info on the AsyncMockFactory is here: http://scalamock.org/user-guide/integration/

**Comment by tfayruzov** [comment]
Thank you for the explanation. I'm not deeply familiar with the framework internals and there seem to be no note of this restriction in the documentation (the fact that I should use the same instance of `MockFactory` between test and mock creation). It sounds kinda logical now, but not apparent from the documentation. Maybe worth to add that explanation?

For completeness, working code is pasted below.

```
import org.scalamock.function.MockFunction2
import org.scalamock.scalatest.{AsyncMockFactory, MockFactory}
import org.scalatest.{AsyncFunSpec, Matchers}

import scala.concurrent.{ExecutionContext, Future}

class AsyncTestRepro extends AsyncFunSpec with Matchers with AsyncMockFactory {

  it("works as expected") {
    val mockExecute = mockFunction[Int, ExecutionContext, Future[Int]]("mockedFunction")
    val mockClient  = new MockClient(mockExecute)

    val logic = new AsyncLogic(mockClient)

//    mockExecute.expects(*, *).returns(Future.successful(1)).never - fails as expected
    mockExecute.expects(*, *).returns(Future.successful(1)).once //succeeds
//    mockExecute
//      .expects(*, *)
//      .returns(Future.successful(1))
//      .twice - fails as expected

    logic.run(1).map(_ should equal(1))

  }
}

trait Client {
  def execute(i: Int)(implicit ec: ExecutionContext): Future[Int]
}

class MockClient(mockExecute: MockFunction2[Int, ExecutionContext, Future[Int]])
    extends Client
    with MockFactory {
  override def execute(i: Int)(implicit ec: ExecutionContext) =
    mockExecute(i, ec)
}

class AsyncLogic(client: Client) {
  def run(i: Int)(implicit ec: ExecutionContext): Future[Int] = client.execute(i)
}
```
