### ISSUE TITLE
NullPointerException trying to use AsyncMockFactory in async scalatest

### ISSUE THREAD

**Issue by lj-ditrapani** [paulbutcher/ScalaMock#215]
### ScalaMock Version
4.0.0

### Scala Version
2.12.4

### Runtime
JVM 1.8

### Please describe the expected behavior of the issue
Using "scalatest" % "3.0.5" & sbt.version=1.1.0, I expect to execute simple async test using AsyncMockFactory.

### Please provide a description of what actually happens
Examples compile, but throw NullPointerException at runtime.

### Reproducible Test Case

```scala
package example

import org.scalamock.scalatest.AsyncMockFactory
import org.scalatest.AsyncFreeSpec

class ExampleTest extends AsyncFreeSpec {
  "runs fine" in {
    succeed
  }

  "this also runs fine" in {
    scala.concurrent.Future.successful { assert(true) }
  }
}

class AsyncExampleTest extends AsyncFreeSpec with AsyncMockFactory {
  "NPE!" in {
    succeed
  }

  "NPE again!" in {
    scala.concurrent.Future.successful { succeed }
  }

  "NPE a 3rd time!" in {
    trait Trait {
      def foo(): Int
    }
    val x = mock[Trait]
    (() => x.foo()).expects().returning(5)
    scala.concurrent.Future.successful { assert(x.foo() == 5) }
  }
}
```

Also, if I try to downgrade to scalamock 3.6.0, I get 
```
[error] /home/blah/scalamock-example/src/test/scala/example.scala:3:12: object scalamock is not a member of package org
[error] import org.scalamock.scalatest.AsyncMockFactory
[error]            ^
```

**Comment by barkhorn** [comment]
Hi I just recently merged PR #214 which sounds very similar. Could you please try the latest snapshot build  and let me know if that works?

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"

and scalamock version "4.1.0-SNAPSHOT"

**Comment by lj-ditrapani** [comment]
4.1.0-SNAPSHOT works properly.

**Comment by lj-ditrapani** [comment]
BTW, thanks for the quick response!

**Comment by barkhorn** [comment]
Will add a comment here when 4.1.0 is published (aiming for Feb 17th)

**Comment by mucahitkantepe** [comment]
Getting same error in version 4.0.0

4.1.0-SNAPSHOT works.

**Comment by barkhorn** [comment]
4.1.0 is syncing with maven central right now
