### ISSUE TITLE
False positive satisfied expectations

### ISSUE THREAD

**Issue by pinguinson** [paulbutcher/ScalaMock#218]
tl;dr Depending on where you define mocks your expectations might or might not be properly checked

### Please describe the expected behavior of the issue

Second tests in all of the ExampleOneTest, ExampleTwoTest and ExampleThreeTest suites fail.

### Please provide a description of what actually happens

Only the one in ExampleOneTest fails.

### Reproducible Test Case

https://github.com/pinguinson/scalamock-bug

**Comment by barkhorn** [comment]
This is expected behaviour.
A test suite needs to mix in MockFactory so the assertions are verified at the end of the test.
Your usage with the separate trait is not a valid scenario.
Please read http://scalamock.org/quick-start/ for more info. Your ExampleOneTest looks fine too.

**Comment by pinguinson** [comment]
Well, that's unfortunate, defining all mocks in a single trait is very handy when you're using something like macwire. This way you can create an instance of the class you're testing with a single `wire` macro: 
`trait Wiring extends AllTheMocks { val someClass = wire[someClass] }`. 

By the way, we're currently using mockito and it allows this kind of behaviour.

**Comment by barkhorn** [comment]
You can probably do that with ScalaMock too, but the MockFactory MUST be mixed into the test suite for the validation to work - unless you can live with a stub?

There is the `Mock` trait which you could try use in the way you have in test2/3 : https://github.com/paulbutcher/ScalaMock/blob/master/shared/src/main/scala/org/scalamock/clazz/Mock.scala
Might need to trick a bit to supply the implicit parameter for it. It's not something I've tried before.

**Comment by pinguinson** [comment]
Thanks for the suggestion, I was able to make it work with shared `Mocks` trait (actually, an abstract class now): https://github.com/pinguinson/scalamock-bug/pull/1/files
