### ISSUE TITLE
ScalaMock doesn’t stub `notify` method

### ISSUE THREAD

**Issue by danielyli** [paulbutcher/ScalaMock#220]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)

ScalaMock 4.1.0

### Scala Version (e.g. 2.12)

Scala 2.11 and Scala 2.12 (reproducible on both)

### Runtime (JVM or JS)

JVM

### Please describe the expected behavior of the issue

```
trait HasNotifyMethod {
  def notify(x: Int): Int
}

stub[HasNotifyMethod]      // <-- this should work
```

### Please provide a description of what actually happens

The `notify` method, which is a member of `java.lang.Object`, isn’t stubbed by ScalaMock:

**Compilation error:** `error: object creation impossible, since method notify in trait HasNotifyMethod of type (x: Int)Int is not defined`

### Reproducible Test Case

See above.

**Comment by barkhorn** [comment]
Hi, have you tried the suggestion from the FAQ? http://scalamock.org/user-guide/faq/
Typically, ScalaMock removes methods inherited from `Object` as that can cause issues, particularly with `equals` and `toString`. Mocking `notify` should be possible, I don't think ScalaMock has a dependency on that. Will have to check though

**Comment by danielyli** [comment]
I’ll have to try the workaround, but this still seems to be a bug. The signature in `Object` is `void notify()`; my example signature in `HasNotifyMethod` is `notify(Int): Int`. Simply having the method name in common shouldn’t affect its ability to be mocked.

**Comment by barkhorn** [comment]
Oh yes. Looks like we don't check the full signature then in `MacroUtils.isMemberOfObject`. I'll have a closer look.

**Comment by aaabramov** [comment]
Today I faced this issue. Any chance to fix this? Because renaming trait methods due to bug it test library seems irrational

**Comment by barkhorn** [comment]
any contributions are more than welcome, but there is no fix for this yet.
