### ISSUE TITLE
Mock trait raise null error

### ISSUE THREAD

**Issue by JustinYiminZhao** [paulbutcher/ScalaMock#222]
trait Example{
  def some_value = "some value"
  println(some_value)
}
when mock this trait and run test, then raise "java.lang.NullPointerException" error.

**Comment by barkhorn** [comment]
The `println` call happens at construction time. Mocks are subclasses, so there is no implementation of `some_value` when the test is run. You will have to change the design to make it work. Generally it's a bad pattern to run non-final methods in a constructor.

**Comment by JustinYiminZhao** [comment]
thanks for your answer, I'll try to change the pattern
