### ISSUE TITLE
Eta-expansion of zero-argument method values is deprecated

### ISSUE THREAD

**Issue by jpork** [paulbutcher/ScalaMock#224]
Using scala-2.12.4, java9 and scalamock-3.6.0 I get for the follwing code:

```
val process = stub[Process]
    (process.getInputStream _ ).when().returns(new ByteArrayInputStream("data".getBytes(UTF_8)))
```

the following Eta-expansion deprecation warning:

```
Eta-expansion of zero-argument method values is deprecated. Did you intend to write process.getInputStream()?
    (process.getInputStream _ ).when().returns(new ByteArrayInputStream("data".getBytes(UTF_8)))
```

What can I do in order to prevent this warning?

**Comment by barkhorn** [comment]
I recently merged a PR which sounds similar: #219 

that changed
       `(mockTurtle.penUp _) expects ()`
to
       `(() => mockTurtle.penUp) expects ()`

Keep in mind that Scalamock 3.6.0 is not supported anymore, you should consider using 4.1.0 now.
