### ISSUE TITLE
AsyncMockFactory fails with compiler flag -Xcheckinit

### ISSUE THREAD

**Issue by by-dam** [paulbutcher/ScalaMock#226]
### Description

When scalac option `-Xcheckinit` is enabled tests which extends the `AsyncMockFactory` fail with the following error when calling `stub[T]` or `mock[T]`:
```
scala.UninitializedFieldError: Uninitialized field: .....: 
[info]   at .....
[info]   at org.scalamock.scalatest.AsyncMockFactoryBase.withExpectations(AsyncMockFactoryBase.scala:36)
[info]   at org.scalamock.scalatest.AsyncMockFactoryBase.withExpectations$(AsyncMockFactoryBase.scala:35)
```

That's because `AsyncMockFactory` extends `AsyncMockFactoryBase` which doesn't initialize the following fields (inherited from `MockContext`):

- `callLog`
- `expectationContext`
- `currentExpectationContext`

`MockFactoryBase` calls `initializeExpectations()` inside the constructor but not `AsyncMockFactoryBase`. 

Obviously calling `initializeExpectations()` directly from `AsyncMockFactoryBase` would fix this but I am not aware of the implications of doing so in the async case (I suspect there are good reasons not to do so).

**Comment by barkhorn** [comment]
This looks like a false-positive to me. `withExpectations` already initialises all fields

**Comment by by-dam** [comment]
Thanks for the quick answer but afaik `withExpectations` is called too late - after the test class is instantiated (inside `withFixture`) - and doesn't avoid the `scala.UninitializedFieldError`.

Problem is the following:

```scala
import org.scalamock.scalatest.AsyncMockFactoryFix
import org.scalatest.{AsyncWordSpec, Matchers}

trait Foo
class CheckInitSpec extends AsyncWordSpec with Matchers with AsyncMockFactory {
  "AsyncMockFactory" should {
    "not have uninitialised members" in {
       val foo = mock[Foo]
    }
  }
}
```

The above code fails with scalac option: `-Xcheckinit` (but is ok without it).

When the fields are initialised (i.e. not null) everything is ok xeven with `-Xcheckinit` enabled. (see below example):

```scala
import org.scalamock.scalatest.AsyncMockFactory
import org.scalatest.{AsyncWordSpec, Matchers}

trait Foo
class CheckInitSpec extends AsyncWordSpec with Matchers with AsyncMockFactoryFix {
  "CheckInit" should {
    "have initialised all members" in {
       val foo = mock[Foo]
    }
  }
}
```
where `AsyncMockFactoryFix` is just a trait initialising the fields:

```scala
package org.scalamock.scalatest

import org.scalamock.context.CallLog
import org.scalamock.handlers.UnorderedHandlers

trait AsyncMockFactoryFix extends AsyncMockFactory {
  val initialHandlers = new UnorderedHandlers
  callLog = new CallLog
  expectationContext = initialHandlers
  currentExpectationContext = initialHandlers
}
```

**Comment by barkhorn** [comment]
Interesting. So the switch complains about any fields that are left as null after construction?
Could you submit a pull request with your proposed changes to `AsyncMockFactory`?
