### ISSUE TITLE
It's apparently impossible to verify that a stubbed method runs only once

### ISSUE THREAD

**Issue by johnomalley** [paulbutcher/ScalaMock#228]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)
4.1.0

### Scala Version (e.g. 2.12)
2.12

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
There should be a way to verify that a stubbed method runs only once.  According to https://scalamock.org/user-guide/advanced_topics/ :

> By default, mocks and stubs expect exactly one call

### Please provide a description of what actually happens
I cannot find a way to verify that a stubbed method runs only once.  I've tried using expects() but that fails with a ClassCastException.  See example code - the test does not fail.

### Reproducible Test Case

```scala
package service.metadata

import org.scalamock.scalatest.MockFactory
import org.scalatest.{FunSpec, Matchers, OneInstancePerTest}

trait Stubbed {
  def fn(): Unit
}

class Subject(stubbed: Stubbed) {
  def fn() {
    stubbed.fn()
  }
}

class ExampleSpec extends FunSpec with Matchers with MockFactory with OneInstancePerTest {
  val stubbed = stub[Stubbed]
  val subject = new Subject(stubbed)

  it("allows multiple invocations") {
    (stubbed.fn _).when().once

    subject.fn()
    subject.fn() // shouldn't the test fail?
  }
}
```

**Comment by johnomalley** [comment]
You can use verify, which works fine.  But I think at minimal the documentation is misleading.

**Comment by barkhorn** [comment]
This behaviour is documented in good detail here: http://scalamock.org/user-guide/mocking_style/
under record-then-verify 

There are also some examples here: https://github.com/paulbutcher/ScalaMock/tree/master/examples/shared/src/test/scala/com/example/makro/mockitostyle

If you think there's room for improvements in the documentation then feel free to submit a PR, but i'd say it's all in there.

**Comment by johnomalley** [comment]
That documentation is great.  My point is that the verbiage "By default, mocks and stubs expect exactly one call" appears to be incorrect.

**Comment by barkhorn** [comment]
which page is that on? or is that in the scaladocs somewhere?

**Comment by johnomalley** [comment]
http://scalamock.org/user-guide/advanced_topics/

Under the heading “call count”. Thanks.

**Comment by barkhorn** [comment]
This sounds better? e395f5b401453678b9f51ed6888260d5644330f7

**Comment by johnomalley** [comment]
That's perfect - thanks.
