### ISSUE TITLE
Add ability to capture arguments

### ISSUE THREAD

**Issue by vakhtang** [paulbutcher/ScalaMock#234]
As far as I can tell ScalaMock lacks the ability to capture arguments a la Mockito's `ArgumentCaptor`. [This StackOverflow post](https://stackoverflow.com/questions/12368938/can-you-capture-and-inspect-arguments-supplied-to-a-method-under-test-with-scala) alludes to a mechanism that exists under-the-hood. It'd be great to expose it, or if it doesn't actually exist, add it. I imagine this can be implemented as a custom matcher.

**Comment by barkhorn** [comment]
See http://scalamock.org/user-guide/advanced_topics/ , topic "Returning values (onCall)"
In your `onCall` function, just save the value you're interested in into some field you defined above - done.

It's neither internal or undocumented :)

**Comment by vakhtang** [comment]
I'm aware of that, and was looking for something a bit more first-class, but ok!

**Comment by vakhtang** [comment]
Yes, more sugar. Perhaps something like this:

```scala
trait Foo {
  def increment(a: Int): Int
}

val fooMock = mock[Foo]
val captor = capture[Int]

(foo.increment _).expects(captor).once()

println(captor.value)
```

**Comment by barkhorn** [comment]
got something on a branch that works like this:

```scala
  it should "capture the arguments of mocks - capture one" in {
    val m = mock[TestTrait]
    val c1 = CaptureOne[Int]()

    m.oneParam _ expects capture(c1) once()
    m.oneParam(42)
    c1.value should be (42)
  }

  it should "capture the arguments of mocks - capture all" in {
    val m = mock[TestTrait]
    val c = CaptureAll[Int]()

    m.oneParam _ expects capture(c) repeat 3
    m.oneParam(99)
    m.oneParam(17)
    m.oneParam(583)
    c.value should be (583)
    c.values should be (Seq(99, 17, 583))
  }
```

I'll push it later and you can review / comment @vakhtang  ?

**Comment by vakhtang** [comment]
Looks great, thanks!
