### ISSUE TITLE
mocking class with private constructor

### ISSUE THREAD

**Issue by kostaskougios** [paulbutcher/ScalaMock#246]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)
4.1.0

### Scala Version (e.g. 2.12)
2.11.8

### Runtime (JVM or JS)
jdk8

### Please describe the expected behavior of the issue
When the default constructor of a class is private, mock[Class] fails with a compilation error

### Please provide a description of what actually happens
I am trying to mock Spark's Dataset which has 1 private and 2 public costructors. The default constructor is
class Dataset[T] private[sql](
    @transient val sparkSession: SparkSession,
    @DeveloperApi @InterfaceStability.Unstable @transient val queryExecution: QueryExecution,
    encoder: Encoder[T])

and mock tries to use that one. Compilation fails.

### Reproducible Test Case

mock[Dataset[X]]

**Comment by barkhorn** [comment]
ScalaMock can only use the default constructor, by trying to fill it in with nulls.
I suggest you extend the `Dataset[X]` class using one of the public constructors and then mock your subclass. I.e.
```
class MockableDataset extends Dataset(null.asInstanceOf[SparkSession], null.asInstanceOf[LogicalPlan], null.asInstanceOf[Encoder[_]])

val mock = mock[MockableDataset]
```

That may work, but if the constructor of the base class runs code, that code will run for each mock also.
For example, `queryExecution.assertAnalyzed()`, `encoderFor(encoder)` and possibly more would run.
That cannot be changed without bytecode manipulation.
Further, as this refers to Spark, you may get very interesting problems when mocks and ScalaTest stuff pass through Kryo or Tungsten.

**Comment by barkhorn** [comment]
`mock[X]` exists in two flavours - one using Scala macros, another using j.l.r.Proxy.
The macro implementation hooks into the compiler phase to generate code, specifically an anonymous subclass of the type to mock with all non-private methods replaced by calls into the ScalaMock core (to count calls, assert, ...).

I have revived an experiment using CGLib that Paul started a while back to be able to expand what can be mocked, but this hasn't progressed much - still learning how this works!

Objenesis might be another thing worth looking at to get around constructor issues specifically and is probably easier to weave into the current implementation. Do you have much experience with it?

**Comment by barkhorn** [comment]
This seems actually pretty simple.
Let me see if I can push a snapshot build with that instantiation method.

```
import com.tr.kraken.qa.ObjenesisTest.MyDS
import org.apache.spark.sql.{Dataset, Encoder, SparkSession}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.objenesis.{ObjenesisSerializer, ObjenesisStd}
import org.scalamock.scalatest.MockFactory
import org.scalatest.{FunSuite, Matchers}

class ObjenesisTest extends FunSuite with MockFactory with Matchers {

  test("objenesis") {
    val objenesis = new ObjenesisStd()
    //val objenesisSer = new ObjenesisSerializer()
    val thingyInstantiator = objenesis.getInstantiatorOf(classOf[MyDS])

    val foo1 = thingyInstantiator.newInstance()
    foo1 should be (a[Dataset[_]])
  }

}

object ObjenesisTest {
  class MyDS extends Dataset[String](null.asInstanceOf[SparkSession], null.asInstanceOf[LogicalPlan], null.asInstanceOf[Encoder[String]])
}
```

**Comment by barkhorn** [comment]
This actually seems quite simple - I'll try to build a SNAPSHOT with this method in it.

```
import org.foo.ObjenesisTest.MyDS
import org.apache.spark.sql.{Dataset, Encoder, SparkSession}
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
import org.objenesis.{ObjenesisSerializer, ObjenesisStd}
import org.scalamock.scalatest.MockFactory
import org.scalatest.{FunSuite, Matchers}

class ObjenesisTest extends FunSuite with MockFactory with Matchers {

  test("objenesis") {
    val objenesis = new ObjenesisStd()
    //val objenesisSer = new ObjenesisSerializer()
    val thingyInstantiator = objenesis.getInstantiatorOf(classOf[MyDS])

    val foo1 = thingyInstantiator.newInstance()
    foo1 should be (a[Dataset[_]])
  }

}

object ObjenesisTest {
  class MyDS extends Dataset[String](null.asInstanceOf[SparkSession], null.asInstanceOf[LogicalPlan], null.asInstanceOf[Encoder[String]])
}
```

**Comment by kostaskougios** [comment]
It should work. I also thing you don't need to subclass Dataset (unless you tried to emulate what the macro is doing), i.e.

val thingyInstantiator = objenesis.getInstantiatorOf(Dataset[String])
