### ISSUE TITLE
Spying on an implementation

### ISSUE THREAD

**Issue by micheal-hill** [paulbutcher/ScalaMock#249]
Is there any way provided by ScalaMock that I could use to spy on the calls being made to the implementation of a method? 

Specifically, I have an class that can be approximated like so:
```scala
class Foo {
  def fetchAll(filter: Filter) = ???
  def fetchAndUpdateAll(filter: Filter) = ???
}
```

I currently have tests that describe the behaviour of `fetchAll`, however I want to test that `fetchAndUpdateAll` should delegate to `fetchAll`. Is there a standard way that I could leave the implementation of `fetchAll` unchanged except that I can later assert things like `fetchAll.expects(filter).once()`?

**Comment by barkhorn** [comment]
Sorry, but no. Partial mocks or spies are not a feature of ScalaMock.
The way it works is to replace all public methods with dummy implementations that can be stubbed out.
There is no way to leave some methods intact and others torn off / converted and likely will never be.

A question i would have is why you want to test the implementation of `fetchAndUpdateAll`. The fact that it delegates to another method isn't really a description of its behaviour / external API, but a detail of *how* it is implemented.
Would it not be better if you test it the same way as `fetchAll`, if both methods are expected to behave the same way, and have the same externally perceived contract?
