### ISSUE TITLE
Expectations defined outside of scope of mock object creation cause NPE's

### ISSUE THREAD

**Issue by spiffxp** [paulbutcher/ScalaMock#25]
``` scala
import org.scalatest.{FunSuite, OneInstancePerTest}
import org.scalamock.scalatest.MockFactory

trait Foo {
  def foo (i: Int): Int
}

class JUnitStyleFixtureTest extends FunSuite with OneInstancePerTest with MockFactory {
  val fix = mock[Foo]

  test("this shouldn't cause an NPE") {
    (fix.foo _) expects (1)
    fix.foo(1)
  }
}
```

```
> test-only JUnitStyleFixtureTest
[info] JUnitStyleFixtureTest:
[info] - this shouldn't cause an NPE *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at org.scalamock.FakeFunction.handle(FakeFunction.scala:37)
[info]   at org.scalamock.FakeFunction1.apply(FakeFunction.scala:53)
[info]   at JUnitStyleFixtureTest$$anon$1.foo(JUnitStyleFixtureTest.scala:9)
[info]   at JUnitStyleFixtureTest$$anonfun$1.apply$mcV$sp(JUnitStyleFixtureTest.scala:13)
...
```

The problem looks to be that when `FakeFunction` is instantiated, its `MockFactoryBase` hasn't yet initialized some of its expectation-related state.  

It seems like there needs to be a way for [`resetExpectations`](https://github.com/paulbutcher/ScalaMock/blob/master/core/src/main/scala/org/scalamock/MockFactoryBase.scala#L130-133) to carry through to all mocks created by a given `MockFactoryBase`.

Some failed attempts to fix:
- Switching from `val` to `lazy val` [here](https://github.com/paulbutcher/ScalaMock/blob/master/core/src/main/scala/org/scalamock/FakeFunction.scala#L32-33) broke `ConcurrencyTest`
- Adding `initialValue` to `ThreadLocal` [here](https://github.com/paulbutcher/ScalaMock/blob/master/core/src/main/scala/org/scalamock/MockFactoryBase.scala#L154-156) replaced the NPE with an expectations exception

**Comment by fommil** [comment]
I'm still seeing something like this in a sequential WordSpec with scalamock 3.2.1.

I'll see if the workaround fixes it tomorrow.

**Comment by fommil** [comment]
used the workaround, fixed it. Eek, I guess that means there is still a problem with WordSpec.

**Comment by tdrozdowski** [comment]
I'm still seeing this in 3.2.1 as well with the WordSpec as well.  (Testing Akka FSM)  

Its odd - not impacting the mock on which I have a method that requires no parameters.  That one works fine - its the mock with 3 parameters which suddenly has the callLog set to null in the middle of everything, then blam, NPE.

**Comment by tdrozdowski** [comment]
Ok - my issue was concurrency.  The mock I created was put on a child actor, and therefore another thread.  Telling the test to Thread.sleep(1000) gave enough time for the child actor to finish before the test evaluated the results.  *phew*!

**Comment by fommil** [comment]
If you use testkit these sorts of problems can be handled without explicit use of thread.sleep

**Comment by paulbutcher** [comment]
Using sleep to make this kind of problem go away is not a solution. Not only does it make your tests unreasonably slow (if you start to have lots of them with arbitrary sleeps) but it doesn't guarantee to fix the problem.

You need to find a reliable way to allow your test to wait for everything to finish and then evaluate the results. As @fommil says, Akka's testkit is one way to do so.

**Comment by tdrozdowski** [comment]
Understood - TestKit is being used. :)  But my lack of experience with testing (and building) Akka actor systems is feeding into these interesting (and unexpected) side effects.

Thanks!

**Comment by davidB** [comment]
Hi,

I use Testkit, but I have to add Thread.sleep(...) on some test to pass (on local). And The CI Server always failed when build is triggered by commit.

I have a combinaison of Actor and Future.map(...).
Code extracted from  my private project : 
```
class MovesSpec(system: ActorSystem) extends extends TestKit(system) with ImplicitSender with FlatSpecLike with ScalaFutures with MockFactory with OneInstancePerTest with BeforeAndAfterAll with BeforeAndAfterEach {
    def this() = this(ActorSystem("MySpec"))
//...
    val ioServiceMock = mock[IoService]

    "Auth" should "be simulated" in {
        ...
        (ioServiceMock.executeHttpReq _).expects(accessTokenRequest).
                returning(Future.successful(Response(HttpURLConnection.HTTP_OK, "application/x-www-form-urlencoded", readFile("/moves/tokenResponse.json"))))
        (ioServiceMock.getCurrentTimestamp _).expects().returning(0L)
        (ioServiceMock.findAuthRedirect _).expects(cloudId).returning(oauthRedirectUrl).repeat(1)

        val config = ...
        val authService = new Oauth2Controller(ioServiceMock, config)
        authService.startAuthFlow(None)
        val res = authService.receivedAuthCodeAndGetToken("aDeviceId", RequestDef("endpoint", HttpMethod.Get, Map(("code", generatedCode), ("state", "astate")), contentType = "application/x-www-form-urlencoded"))
        assertResult(true, "Invalid result : " + res.futureValue)(res.futureValue.isGood)
        res.futureValue.get shouldEqual info0
    }
...
```
I have the same issue with mock declared inside the test block

Is it possible (as a workaround) to have a method that wait until actual every expected are satisfied or any unexpected call "actual" ?

I use  : 
* scalamock-scalatest-support_2.10:3.2.2
* scalatest_2.10:2.2.4
I run test from eclipse or maven.

Thanks!

**Comment by sebastian-alfers** [comment]
I use TestKit to test an FSM that uses "scaladi" to inject the mock, I created.

@tdrozdowski how did you fix your problem?

**Comment by davidB** [comment]
@sebastian-alfers you can my workaround in the https://github.com/paulbutcher/ScalaMock/issues/101

**Comment by sebastian-alfers** [comment]
The problem is related to scala scheduler (http://doc.akka.io/docs/akka/snapshot/scala/scheduler.html).

I created a sample project that shows the problem if you run the test: https://github.com/sebastian-alfers/akka-fsm-scaldi-scalatest-scalamock/blob/master/src/main/scala/Example.scala#L59

**Comment by Somewater** [comment]
I also have related exception in new version of library
```
ERROR akka.actor.OneForOneStrategy - null
java.lang.NullPointerException: null
	at org.scalamock.function.FakeFunction.handle(FakeFunction.scala:42) ~[scalamock-core_2.10-3.2.1.jar:3.2.1]
	at org.scalamock.function.FakeFunction7.apply(FakeFunction.scala:93) ~[scalamock-core_2.10-3.2.1.jar:3.2.1]
...
```

scala 2.10.4
scalamock 3.2.1 (also try it with 3.2.2 - same error)
akka 2.2.3

**Comment by DWvanGeest** [comment]
For those experiencing an NPE when testing async code, this PR could potentially make it more clear what is going on: https://github.com/paulbutcher/ScalaMock/pull/142.

**Comment by nisarakash** [comment]
I am using Scala 2.11, ScalaTest 3.0 and ScalaMock 3.6.0. When I am trying to mock using following code, I am getting NPE. Please help me.

val cloudWatch = mock[AmazonCloudWatch]

**Comment by barkhorn** [comment]
@nisarakash we have a website at http://scalamock.org/ which has a user guide and an FAQ. If that doesn't answer your questions, you should look at Stackoverflow. The Github issues are not a support forum.
