### ISSUE TITLE
ArgCapture documented but not available

### ISSUE THREAD

**Issue by hudsonmd** [paulbutcher/ScalaMock#251]
### ScalaMock Version (e.g. 3.5.0)
4.1.0

### Scala Version (e.g. 2.12)
2.11

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
To be able to use CaptureOne or find org.scalamock.matchers.ArgCapture in my classpath

### Please provide a description of what actually happens
This class file does not exist although listed in the documentation at https://scalamock.org/user-guide/advanced_topics/ 
Additionally, if you search for this class you will find 0 results on the internet referring to its existence outside of that one page in the docs

### Reproducible Test Case

```scala
test("my failing test") {
  // your imports
import org.scalamock.matchers.ArgCapture
  // code that fails
val a = ArgumentCapture[Int]
}
```

**Comment by barkhorn** [comment]
True. that feature wil be in 4.2.0 - see #242 #241
