### ISSUE TITLE
Stubs of the same class with expectations on same method interfering

### ISSUE THREAD

**Issue by alexm-babylon** [paulbutcher/ScalaMock#262]
### ScalaMock Version (e.g. 3.5.0)
4.1.0

### Scala Version (e.g. 2.12)
2.12.5

### Runtime (JVM or JS)
JVM

### Please describe the expected behavior of the issue
Two stubs of the same class with expectations on the same method should not interact. Instead there are occasional test failures.

### Please provide a description of what actually happens
You can see below that there are expectations on the same User.saveUser method for two different stubs.
```
Expected:
inAnyOrder {
  <stub-81> ModelRestClient.getNode(*) any number of times (called twice)
  <stub-81> ModelRestClient.getValueNode(*, *, *) any number of times (never called)
  <stub-82> User.saveUser(*, *, *, *) any number of times (never called)
  <stub-86> User.saveUser(*, *, *, *) once (never called - UNSATISFIED)
}

Actual:
  <stub-81> ModelRestClient.getNode(990)
  <stub-81> ModelRestClient.getNode(30)
  <stub-86> User.saveUser(12345, 23, 45, akka://test-system) (UserTest.scala:23)
```
Even though the stub-86 method was called and can be seen in the Actual, the Expected says that it was never called. Possible interference with the other stub? Note that this only happens sometimes.

### Reproducible Test Case

There is no reliable way to always make this fail. Seems to happen about 5% of runs locally but more like 50% on build server. Happens more locally when execution is slowed with debugging and breakpoints.
Below is the kind of setup which led to this issue. I don't have time to write up a full test but if there is interest I can provide more.

```scala
test("my failing test") {
  val stub1 = stub[User]
  (stub1.saveUser(_: Int, _: Int, _: Int)(_: ActorSystem)).when(*, *, *, *).returns(Future.successful(()))
  val stub2 = stub[User]
  (stub2.saveUser(_: Int, _: Int, _: Int)(_: ActorSystem)).when(*, *, *, *).returns(Future.successful(())).once()
  val myTestService = new TestService(stub2)
  val result = myTestService.doThingToTest(123)
}
```
As you can see stub1 is unused (in reality, created mistakenly off in some trait) but it leads to the error in the previous section.

**Comment by barkhorn** [comment]
Hi, a few things to note here:

1. The test case you provided is not enough for me to investigate further. You have external dependencies, and clearly use other libraries (assume its some Akka version here). Based on that, I could do anything with this report.

2. Given that the behaviour only happens sporadically, my guess is you use Futures/Promises or some asynchronous mechanism. You will need to synchronise this somehow, and/or use the correct test suite. See http://scalamock.org/user-guide/integration/

3. Stubs do not interact. We actually have a test case for concurrency: https://github.com/paulbutcher/ScalaMock/blob/master/shared/src/test/scala/org/scalamock/test/scalatest/ConcurrencyTest.scala
Access is synchronized: https://github.com/paulbutcher/ScalaMock/blob/34ff22290dbafe8368fa3cba724dd68584a1bbc1/shared/src/main/scala/org/scalamock/handlers/UnorderedHandlers.scala#L27

I doubt you found a bug in ScalaMock here.

**Comment by barkhorn** [comment]
Closing this for now. If you find a 100% reproducible test case, please post and we can revisit the situation.
For help with concurrent tests, please use StackOverflow as a resource.
