### ISSUE TITLE
missing implicit Defaultables when constructing some mocks

### ISSUE THREAD

**Issue by missingfaktor** [paulbutcher/ScalaMock#29]
We are using Akka's dataflow concurrency API which makes a heavy use of delimited continuations. If a class contains a method whose return type is CPS annotated, then ScalaMock fails to mock that class. The compiler error is as follows (in our particular case; hopefully good enough to point at the problem):

``` scala
[error] /opt/gwt/pdp/test/controllers/MarketingPageControllerSpec.scala:21: could not find implicit value for evidence parameter of type org.scalamock.Defaultable[models.Page @util.continuations.cps[scala.concurrent.Future[Any]]]
[error]             val p = mock[PageService]
[error]                         ^
[error] one error found
[error] (test:compile) Compilation failed
```

[ cc: @apgeorge, @mushtaq ]

**Comment by dnrusakov** [comment]
The same problem when mocking javax.jms.TextMessage:
val rawMessageMock = mock[TextMessage]

 could not find implicit value for evidence parameter of type org.scalamock.util.Defaultable[java.util.Enumeration]
[error]           val rawMessageMock = mock[TextMessage]
[error]                                    ^
[error] one error found

Does anybody know how to fix it?

**Comment by barkhorn** [comment]
The problem could  be raw generics.

E.g. with 
`val mockRequest = mock[javax.servlet.http.HttpServletRequest]`
this has
`public Enumeration getHeaders(String name);`

But Enumeration has a type parameter.

**Comment by Yeitijem** [comment]
I had the same error with mocking an interface which has a function which has a java map as return result:
`def getAllParameter: java.util.Map[_, _] = new java.util.HashMap`

Defining an implicit Defaultable for this type has not worked:

`implicit object defaultMap extends Defaultable[java.util.Map[_, _]] { val default: java.util.Map[_, _] = new java.util.HashMap}`

There is still an compiler error:
could not find implicit value for evidence parameter of type org.scalamock.util.Defaultable[java.util.Map]

Should support your theory about its a problem with raw generics

**Comment by barkhorn** [comment]
Example below for `Enumeration` and `Map`, will add this to the documentation too.

```java
public interface RawTypeInterface {
    java.util.Enumeration foo();
    java.util.Map bar();
}
```

```scala
"mocking a java method with raw type" should "work" in {
  implicit val d = new Defaultable[java.util.Enumeration[_]] {
    override val default = null
  }
  implicit val d2 = new Defaultable[java.util.Map[_, _]] {
    override val default = null
  }
  val mockRequest = mock[RawTypeInterface]
}
```
