### ISSUE TITLE
double definition when trying to mock java interface

### ISSUE THREAD

**Issue by fancywriter** [paulbutcher/ScalaMock#314]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version 
4.4.0

### Scala Version 
2.11

### Runtime
JVM

### Please describe the expected behavior of the issue
I would like to mock the IssueRestClient from atlassian API https://bitbucket.org/atlassian/jira-rest-java-client/src/d2b404e1795732e5c81dbdaaa9bc6678d94c2edf/api/src/main/java/com/atlassian/jira/rest/client/api/IssueRestClient.java

### Please provide a description of what actually happens
It doesn't compile, gives the error:
```
Error:(45, 31) double definition:
override def addAttachments(x$1: java.net.URI,x$2: java.io.File*): com.atlassian.util.concurrent.Promise[Void] at line 45 and
override def addAttachments(x$1: java.net.URI,x$2: com.atlassian.jira.rest.client.domain.input.AttachmentInput*): com.atlassian.util.concurrent.Promise[Void] at line 45
have same type after erasure: (x$1: java.net.URI, x$2: Seq)com.atlassian.util.concurrent.Promise
    val issueRestClient = mock[IssueRestClient]
```

### Reproducible Test Case

Please provide a minimised code snippet that fails, ideally, written as a failing test case in ScalaTest.
This will help us a lot in diagnosing the problem and work on a fix.
If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

```scala
test("my failing test") {
  // your imports
  import com.atlassian.jira.rest.client.IssueRestClient
  // code that fails
  val issueRestClient = mock[IssueRestClient]
}
```

**Comment by barkhorn** [comment]
Java varargs are represented by a sequence in Scala. E.g. `java.io.File...` becomes `Seq[java.io.File]`.
So after compilation, type erasure makes this a `Seq[Any]` as that's just how the JVM works.

Do you use both methods?
Not sure if that will work, but you could declare an abstract *Java* class that implements one of the two methods, but with a final qualifier. Then just mock that type instead of your interface.
Scalamock will not attempt to stub out any final methods (as that wouldn't work).

**Comment by fancywriter** [comment]
No, don't use any of them in fact. Using other methods. In fact things this interface is too huge, not perfect API design. 🙄 
Could try the trick with abstract class or another interface extending it... good point.

**Comment by barkhorn** [comment]
did you have success with that approach? Would be cool if you could share any code snippets for anyone else coming across this issue

**Comment by fancywriter** [comment]
@barkhorn yes, it helped, thank you very much!
I have tried with scala abstract class, didn't work. had to write java class, indeed. Some sort of
```
public abstract class TestIssueRestClient extends IssueRestClient {
   public final addAttachments(URI uri, File... files): Promise[Void] {
      return Promises.promise(null);
   }
}
...
val client = mock[TestIssueRestClient] // compiles well
```

**Comment by barkhorn** [comment]
thanks for sharing that :)
