### ISSUE TITLE
Unable to mock AWS Ec2AsyncClient

### ISSUE THREAD

**Issue by brendo-m** [paulbutcher/ScalaMock#315]
*If you want to discuss a new feature, please ignore/clear this form.*

### ScalaMock Version (e.g. 3.5.0)

`3.6.0`

### Scala Version (e.g. 2.12)

`2.12.7`

### Runtime (JVM or JS)

`JVM`

### Please describe the expected behavior of the issue

`org.scalamock.scalatest.MockFactory` should be able to mock a `Ec2AsyncClient` from the AWS Java SDK v2.

### Please provide a description of what actually happens

I get an error like so:

```
[scalac-2.12] error: Could not write class Repro$$anon$1 because it exceeds JVM code size limits. Method <init>'s code too large!                                                                                 
```

### Reproducible Test Case

```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.FunSuite
// libraryDependencies += "software.amazon.awssdk" % "ec2" % "2.13.9" % Test
import software.amazon.awssdk.services.ec2.Ec2AsyncClient

class Repro extends FunSuite with MockFactory {
  test("repro") {
    val mockEc2 = mock[Ec2AsyncClient]
  }
}
```

**Comment by barkhorn** [comment]
I just had a glance at the javadoc for this interface. 
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/Ec2AsyncClient.html
The number of methods is just absurd, but I guess this happens as AWS uses a lazy code generator to just shove everything into one interface.

ScalaMock needs to implement every single method on this as they are are all public, and the resulting class needs to be instantiable, so all interface contracts must be satisfied.
To facilitate a mock and redirect invocations to the CallHandlers for recording and responding, a certain amount of code is needed and I can't see how this could be reduced - it would be such a fundamental change in the library that it wouldn't even be the same thing anymore.

Three suggestions:
1. This report is for is a rather old version of ScalaMock. Do you get the same issue with the latest version?
2. Did you have a look at Proxy Mocks (part of scalamock)? Given that his is an interface, it should work and maybe the JVM internal proxying mechanism is a little more leightweight in this scenario
3. If neither of the above works, maybe you could create your own interface with the subset of methods you REALLY need. I'd imagine it's not all of them. Then link your code against that and mock something much smaller as a result.

**Comment by barkhorn** [comment]
Here's a proxy mock example; https://github.com/paulbutcher/ScalaMock/blob/master/jvm/src/test/scala/com.paulbutcher.test/proxy/ProxyMockTest.scala

**Comment by brendo-m** [comment]
Unfortunately I'm stuck with `3.6.0` for now, but the proxy mock worked perfectly! Thanks for the quick response

**Comment by barkhorn** [comment]
thanks for sharing your feedback @brendo-m. 
As there is a viable solution in this case and it relates to an older version or ScalaMock, i'll close this for now

**Comment by falken** [comment]
I can confirm the same behavior with ScalaMock 4.4.0. @brendo-m can you help with some sample code of how you used the ProxyMock?

**Comment by brendo-m** [comment]
@falken sorry for the delay, try this out

```
import java.util.concurrent.CompletableFuture

import org.scalamock.proxy.Mock
import org.scalamock.scalatest.proxy.MockFactory
import org.scalatest.{FunSuite, Matchers}
import software.amazon.awssdk.services.ec2.model.{DescribeInstancesRequest, DescribeInstancesResponse}
// libraryDependencies += "software.amazon.awssdk" % "ec2" % "2.13.9" % Test
import software.amazon.awssdk.services.ec2.Ec2AsyncClient

class ReproTest extends FunSuite with MockFactory with Matchers {
  def describeInstances(ec2: Ec2AsyncClient) =
    ec2.describeInstances(DescribeInstancesRequest.builder.build)

  test("repro") {
    val mockEc2: Ec2AsyncClient with Mock = mock[Ec2AsyncClient]

    val request = DescribeInstancesRequest.builder.build
    val response = DescribeInstancesResponse.builder.build

    mockEc2.expects('describeInstances)(request).returning(CompletableFuture.completedFuture(response))

    describeInstances(mockEc2).get() shouldEqual response
  }
}
```
