### ISSUE TITLE
ScalaMock 3.0.1 problem with a class with constructor arguments 

### ISSUE THREAD

**Issue by NazneenRupawalla** [paulbutcher/ScalaMock#33]
We are using ScalaMock 3.0.1 with Spec2 and Scala 2.10

libraryDependencies +=
  "org.scalamock" %% "scalamock-specs2-support" % "3.0.1" % "test"

When we try to mock a class with constructor arguments 

i.e

class Test(number:Int)
val arg=Mock[Test]

We get the following error

error: not enough arguments for constructor Test: (number: Int)Test.
Unspecified value parameter number.
val arg= mock[Test]

Could you please let us know if this is an existing issue and if there is any way to overcome it?
Thanks.

**Comment by trienism** [comment]
This kind of seems like a big deal, is there any ETA for this issue?

**Comment by sebastian-alfers** [comment]
Ping

**Comment by paulbutcher** [comment]
I'm afraid that ScalaMock is basically waiting for scala.meta to be released. We've tried (and tried, and tried!) to get Scala's current macro support to play ball, and every approach we've tried has hit one roadblock or another (you can see various different attempts in the branches in GitHub).

We'll have another go when scala.meta is available, and hopefully this time the support will be up to the job.

No pressure @xeno-by ;)

**Comment by MrPowers** [comment]
@paulbutcher - Looks like scala.meta has been released!  Any update on [when ScalaMock 4 will be released](http://scalamock.org/roadmap/)?  Thanks for the awesome work you've done with this project!

**Comment by m-tanner** [comment]
Hi @paulbutcher :) Are there any plans to address this issue?
