### ISSUE TITLE
None of verify().once()   verify().never()    verify().twice() on the same stub fail

### ISSUE THREAD

**Issue by kolov** [paulbutcher/ScalaMock#337]
### ScalaMock Version (e.g. 3.5.0)
5.0.0
### Scala Version (e.g. 2.12)
2.12
### Runtime (JVM or JS)
JVM
### Please describe the expected behavior of the issue
The test should fail
### Please provide a description of what actually happens
the test passes
### Reproducible Test Case

Please provide a minimised code snippet that fails, ideally, written as a failing test case in ScalaTest.
This will help us a lot in diagnosing the problem and work on a fix.
If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

```scala
import org.scalamock.scalatest.MockFactory
import org.scalatest.{FlatSpecLike, Matchers}

trait A {
  def foo(): Int
}

class BadSpec extends FlatSpecLike with Matchers {

  it should "verify stubs" in new TestScopeA {
    (a.foo _).when().returns(4)

    (a.foo _).verify().once()
    (a.foo _).verify().never()
    (a.foo _).verify().twice()
  }

}

class TestScopeA extends MockFactory {
  val a = stub[A]
}
```

**Comment by barkhorn** [comment]
You are using the fixture wrong. Change your code to this and it will work as you want it:

```scala
trait A {
  def foo(): Int
}

class Issue337BadSpec extends AnyFlatSpecLike with Matchers with MockFactory {

  class TestScopeA {
    val a = stub[A]
  }

  it should "verify stubs" in new TestScopeA {
    (a.foo _).when().returns(4)

    (a.foo _).verify().once()
    (a.foo _).verify().never()
    (a.foo _).verify().twice()
  }
```

**Comment by kolov** [comment]
Can you point to documentation explaining what makes the first version wrong?

**Comment by barkhorn** [comment]
The documentation for fixtures is here:  https://scalamock.org/user-guide/sharing-scalatest/

MockFactory needs to be mixed in with the TestSuite so the relevant context for the mock/stub is set up correctly. As you had  the fixture outside of the TestSuite, this didn't happen.
