### ISSUE TITLE
Capturing multiple arguments

### ISSUE THREAD

**Issue by twuyts** [paulbutcher/ScalaMock#348]
Feature improvement request:

### ScalaMock Version (e.g. 3.5.0)
5.0.0

### Scala Version (e.g. 2.12)
2.12.

### Please describe the expected behavior of the issue
Capturing multiple arguments is not intuitive: it requires a Capture object per argument, which makes verifying the captures cumbersome

### Reproducible Test Case
```scala
"ScalaMock should capture the arguments of mocks - works, but cumbersome" in {
    trait TestTrait {
      def oneParam(i: Int): Unit
      def twoParam(i: Int, k: Int): Unit
      def threeParam(i: Int, j: Int, k: Int): Unit
    }

    val m = mock[TestTrait]
    val c1 = CaptureAll[Int]()
    val c21 = CaptureAll[Int]()
    val c22 = CaptureAll[Int]()

    m.oneParam _ expects capture(c1)
    m.twoParam _ expects (capture(c21), capture(c22)) repeat 2

    m.oneParam(99)
    m.twoParam(1,2)
    m.twoParam(3,4)
    c1.value should be (99)
    c21.value should be (3)
    c22.value should be (4)
    c21.values should contain theSameElementsInOrderAs Seq(1,3)
    c22.values should contain theSameElementsInOrderAs Seq(2,4)
}
"ScalaMock should capture the arguments of mocks - more intuitive" in {
    trait TestTrait {
      def oneParam(i: Int): Unit
      def twoParam(i: Int, k: Int): Unit
      def threeParam(i: Int, j: Int, k: Int): Unit
    }

    val m = mock[TestTrait]
    val c1 = CaptureAll[Int]()
    val c2 = CaptureAll[(Int, Int)]()
    val c3 = CaptureAll[(Int, Int, Int)]()

    m.oneParam _ expects capture(c1)
    m.twoParam _ expects capture(c2)
    m.threeParam _ expects capture(c3) repeat 2

    m.oneParam(99)
    m.twoParam(1,2)
    m.threeParam(1,2,3)
    m.threeParam(4,5,6)
    c1.value should be (99)
    c2.value should be ((1,2))
    c3.value should contain theSameElementsAs ((1,2,3),(4,5,6))
  }```

**Comment by barkhorn** [comment]
I don't think what you describe above with the multiple arguments in a tuple is actually feasible in the Scala language, as your expectation is to convert from 1 arg of (Int, Int) to 2 args Int, Int dynamically.
It may well create a different problem when the tuple signature also exist and make it ambiguous in syntax.

Have you considered the onCall handler instead of argument captures?
You can write the lambda yourself then and perform more complex comparisons

https://scalamock.org/user-guide/advanced_topics/

**Comment by twuyts** [comment]
You're probably right, I had a closer look at how the capturing works, and indeed, it does not seem possible.
I worked around it by writing my own mock.
