### ISSUE TITLE
ScalaTest Async tests with MockFactory are silently ignored, not documented in QuickStart Guide

### ISSUE THREAD

**Issue by alpex92** [paulbutcher/ScalaMock#371]
### Please describe the expected behavior of the issue

Quick Start guide should specify that you should use AsyncMockFactory instead of regular MockFactory with ScalaTest async specs. Also it would be cool to have the corresponding message when trying to run tests with MockFactory and AsyncSpec

### Please provide a description of what actually happens

Documentation lacks any information that you should use AsyncMockFactory with Async spec.
Mixing MockFactory to any AsyncSpec causes tests to be ignored silently

### Reproducible Test Case

Please provide a minimised code snippet that fails, ideally, written as a failing test case in ScalaTest.
This will help us a lot in diagnosing the problem and work on a fix.
If the issue is more complex or requires configuration, please provide a link to a project on Github that reproduces the issue.

```scala

import org.scalamock.scalatest.MockFactory
import org.scalatest.flatspec.AsyncFlatSpec
import scala.concurrent.Future

class SomeTest
  extends AsyncFlatSpec
    with MockFactory {

// silently ignored
 it should "do something" in {
  Future.successful(assert(true))
}

}
```

**Comment by barkhorn** [comment]
It would be great if you could contribute an example for Async mocking - are you willing to write something simple?

**Comment by Daenyth** [comment]
Related to this, I can't figure out how to write a mocking mixin that works in both versions.

MockContext is private, so you can't take it as an implicit.
The common parent class of MockFactory and AsyncMockFactory is MockContext

Am I missing something?
