### ISSUE TITLE
What are your plans for ScalaMock regarding Scala 3?

### ISSUE THREAD

**Issue by informarte** [paulbutcher/ScalaMock#396]

**Comment by barkhorn** [comment]
I no longer work with Scala in my job, so this project is down to hobbyist interest when I have the time for it. I've been focussing on keeping dependencies up to date and looking at some of the longer standing bugs.
Scala 3 looks very interesting, and the macro system has changed a lot, so it would be a bigger undertaking of creating a version of Scalamock for it. I'd like to do it but can't really make any promises when that might happen
