### ISSUE TITLE
Mock singleton and companion objects

### ISSUE THREAD

**Issue by markusjura** [paulbutcher/ScalaMock#41]
This is a feature request to track the support of singleton and companion objects.

**Comment by allquantor** [comment]
+1

**Comment by lin-zhao** [comment]
+1..

**Comment by vadim-shb** [comment]
+1

**Comment by lderks** [comment]
+1

**Comment by schasse** [comment]
+1

**Comment by magicknot** [comment]
Any news on this?

**Comment by avalon12** [comment]
+1

**Comment by orlandojsjr** [comment]
+1

**Comment by vireshjivane** [comment]
+1

**Comment by orlandojsjr** [comment]
Is there a release date for this?

**Comment by paulbutcher** [comment]
In a word, "no". It depends on ScalaMeta.

**Comment by ches** [comment]
In more than a word, have a look at [this post][1] and the referenced mailing list discussion—perhaps someone interested in this issue with time to research the progress of the macros situation can try to contribute to ScalaMock before Paul gets to it.

[1]: https://paulbutcher.com/2014/04/15/scalamock-status-report/

**Comment by PabloStratio** [comment]
+1

**Comment by previousdeveloper** [comment]
+1

**Comment by avalon12** [comment]
@barkhorn Can you elaborate?

**Comment by barkhorn** [comment]
Elaborate on? I'm still quite new to ScalaMock's codebase.
If anyone has a Pullrequest to suggest for this I'm all ears, otherwise this is probably something for scala meta and v4.

**Comment by avalon12** [comment]
I was referring to your label, I was under the impression that this feature was still being considered. Thanks.

**Comment by barkhorn** [comment]
I have mass-tagged all issues a few days ago to be able to filter on how to approach this backlog and close/work some off. This feature looks quite useful to me, though there are probably workarounds for now (DI, Factories?).

**Comment by avalon12** [comment]
True, actually I think that if you need to be able to do this in your code, your code is not well written, and you should think about using interfaces. Sadly I am not always under full control of what code I am testing.

**Comment by barkhorn** [comment]
This is now mentioned as a known limitation in the FAQ: http://scalamock.org/user-guide/faq/

**Comment by JacopoGobbi** [comment]
no improvements after 6 years?

**Comment by barkhorn** [comment]
After looking into ScalaMeta recently, I am not convinced that this will help here at all, so I'm removing it from the relevant milestone.
Not sure where that leaves this feature, but it's still a fairly low priority compared to some of the other macro-related complications that should be improved first.

Regarding the "no improvement after 6 years" comment - everyone is welcome to contribute a PR to this project if they have a solution, or even propose a pattern towards a solution in this comment thread, that would be appreciated too.

**Comment by JacopoGobbi** [comment]
@barkhorn Thanks for your comment, I will check and hope my knowledge is good enough to help contributing into this issue! :)
