### ISSUE TITLE
Mistake in scalamock documentation

### ISSUE THREAD

**Issue by waagnermann** [paulbutcher/ScalaMock#418]
Hi, I found a little mistake in documentation’s [quick-start chapter](https://scalamock.org/quick-start/)
![image](https://user-images.githubusercontent.com/33073902/139481670-fdaca3f0-2da2-4fea-add1-a1d9a1200c18.png)

I think that there are
```scala
extends Formatter
```
Instructions missing right after each 3 objects inside the Greeting object, aren’t they? 
please, update the docs if I’m right or redirect the problem to the corresponding contributors. I’ve been facing this missing code segment for quite a long while

**Comment by waagnermann** [comment]
why is this issue closed without any comments and explanations?

**Comment by barkhorn** [comment]
it hasn't, see the link just above your comment
