### ISSUE TITLE
Is this project maintained anymore?

### ISSUE THREAD

**Issue by andreisilviudragnea** [paulbutcher/ScalaMock#423]
There are many new PRs and issues with no response.

@paulbutcher Do you need someone else to take over the project?

**Comment by paulbutcher** [comment]
I handed maintenance over to @barkhorn several years ago. Are you still around Philipp?

**Comment by barkhorn** [comment]
Yes. There will be another release this year to update dependencies and merge PRs. Work has been exceptionally busy so I’m sorrry I had to neglect this project a bit

**Comment by simbo1905** [comment]
I am looking to upgrade to Scala 3 and I don't see any releases for that yet at https://repo1.maven.org/maven2/org/scalamock/ is that on the near term roadmap?

**Comment by barkhorn** [comment]
I've split the Scala 3 discussion out
