### ISSUE TITLE
mocking default arguments

### ISSUE THREAD

**Issue by fernandoracca** [paulbutcher/ScalaMock#43]
when setting expectations for a method with default arguments, the compiler will report ambiguity in the call. 

I had to explicitly set the argument in the test in order for it to complete the expectation.

then, the test would fail with:

once (never called - UNSATISFIED)

So i had to resort to specifying the default value for that parameter in the call. This defeats the purpose of the default argument.

**Comment by rcsenkbeil** [comment]
Does this mean that you should be able to do something like this?

```
class MyClass {
  def myMethod(x: Int = 3) = x + 1
}

val mockMyClass = mock[MyClass]
(mockMyClass.myMethod _).expects(*).returning(999)
```

With ScalaMock 3.2.2, I am still getting the following:

```
Unexpected call: myMethod$default$1()

Expected:
inAnyOrder {
  myMethod(*) once (never called - UNSATISFIED)
}

Actual:
  myMethod$default$1()
```

Is there any documentation that covers this case? I didn't see anything in the examples or tests for ScalaMock.

**Comment by ECHO-FOLLOW-HEART** [comment]
I am a user of scalamock, please update the user-guide of scalamock.
3.2 modified as 3.2.1, thx!

http://scalamock.org/user-guide/installation/

**Comment by fernandomora** [comment]
Still having same problem with ScalaMock 3.2.2:

It works with mocks, .expects(...).returns(...) but fails with stubs .when(...).returns(...)

**Comment by tlync** [comment]
I met the same issue via outdated installation guide on scalamock.org.
Please update the installation on scalamock.org or upload scalamock.org to github!

**Comment by paulbutcher** [comment]
Scalamock.org is already on GitHub :-)

https://github.com/paulbutcher/ScalaMock/tree/gh-pages

**Comment by karpoftea** [comment]
Met the same issue. Please, update installation guide to save others time.

**Comment by paulbutcher** [comment]
As I mentioned in the comment above, the installation guide is available on GitHub. I'd be delighted to accept a pull request.

**Comment by dskrvk** [comment]
Still having the same problem with 3.2.2 when doing `(mock.func _).expects().returns()`.

**Comment by ebenini-mdsol** [comment]
Still having the same problem here with scalaMock 3.5 and proxy.MockFactory
```Unexpected call: getStuff$default$3()```

**Comment by barkhorn** [comment]
Scalamock 3.5 is a pretty old version, please upgrade
