### ISSUE TITLE
Deprecation warning caused by upgrade to 2.10.3

### ISSUE THREAD

**Issue by cb372** [paulbutcher/ScalaMock#53]
```
[warn] /Users/c-birchall/projects/ScalaMock/core/src/main/scala/org/scalamock/Mock.scala:209: method TypeDef in trait Trees is deprecated: Use the canonical TypeDef constructor to create an abstract type or type parameter and then initialize its position and symbol manually
[warn]           m.typeParams map TypeDef _,
[warn]                            ^
[warn] one warning found
```

The deprecated factory method (`reflect.api.Trees#TypeDef(Symbol)`) relies on a lot of stuff in `reflect.internal.Symbol`, and I don't see how to easily recreate that using only the public API.

**Comment by barkhorn** [comment]
project still builds with 2.10,2.11,2.12 at the moment. There are deprecation warnings, but doesn't look like any immediate action needs to be taken
