### ISSUE TITLE
Fail fast for excessive mock calls

### ISSUE THREAD

**Issue by Kylerow** [paulbutcher/ScalaMock#55]
I'm not sure if this is the forum you prefer - but I created an interesting problem for myself using scalamock - I was testing something in a separate thread that needed to have a particular condition in order to stop doing its business (and in the case of the test, to stop call my mock function).  So being the brilliant developer I am - I chose not to set that stop condition and moved on to the next test.  The tests would intermittently take a long time to run, would use up all available memory and would occasionally hang.  

I whipped out visualvm to troubleshoot - and saw a bunch of "Call" objects (millions) - and realized probably in the CallLog class, it keeps references to every call made.  

I know this was my mistake - but a handy feature would be a quick blow up on this after some arbitrary threshold - maybe a threshold based on the available heap or something - or I don't know - even just an arbitrary number of calls.  

I may offer a pull request if I can work something out quickly.....and you may not even want this, but I thought I'd post it here.

**Comment by barkhorn** [comment]
Implemented. can be set with `-Dscalamock.calls.warn=10000` 
ScalaMock will then warn in intervals of 10000 (at >10000, >20000, ...).
Default value is Int.MaxValue (basically disabled then).
