### ISSUE TITLE
Allow clean-up code to be executed after verify was called

### ISSUE THREAD

**Issue by DGolubets** [paulbutcher/ScalaMock#61]
```
verify should appear after all code under test has been exercised
```

Hi!
I wonder why does this rule exist? 

I have some test cleanup code that can eventually call one of stubbed members, but I don't care about it as it fall outside of my testing scope.

**Comment by barkhorn** [comment]
After reading this, I think the issue should be rejected.
If the Akka shutdown is part of the test case, then it should be part of the test case/fixture.

What I would suggest is writing a fixture/mixin that starts/stops Akka as a before-/afterEach action.
That has worked well for us in some projects and is quite reusable.
Another pattern is to have a specific "Poison Pill" event sent to acturs that makes them shut down at a specific, controlled point in time.
