### ISSUE TITLE
Issue with mocking overloaded functions

### ISSUE THREAD

**Issue by kiran-kumar** [paulbutcher/ScalaMock#66]
I have a trait with a function overloaded(different in number of parameters and not type of parameters). I am trying to mock one function of the 2 overloaded functions in trait. I see scalamock not able to resolve ambiguity

example code:

trait HBaseStoreProcessor {
def processDataFromStore(adapter : StorageAdapter, tableName : String, metricId : Short, colFamilies : Array[Array[Byte]],  startTime : Long, stopTime : Long, isAggregated : Boolean, validateEntityRowKey : (EntityRowKey) => Boolean):List[DataStoreResult] = { }

def processDataFromStoreWithFilter(adapter : StorageAdapter, tableName : String, metricId : Short, colFamilies : Array[Array[Byte]], 
      startTime : Long, stopTime : Long, isAggregated : Boolean, validateEntityRowKey : (EntityRowKey) => Boolean,filter:Filter) : List[DataStoreResult] = {}  
}

 "DataAccessUtil" must {
    "return empty List[NameAverageTotalTuple] when no data processed from the store" in {
      val mockAdapter = mock[HBaseStoreProcessor]
      val storageAdapter=mock[StorageAdapter]
      inAnyOrder {
        (mockAdapter.processDataFromStore _) expects (*, *, *, *, *, *, *, *)  returning List[DataStoreResult]()
      }
      assert(DataAccessUtil(mockAdapter).calculateAverageTime(storageAdapter, HBaseConstants.NodeStats(900), 100, 100, 200, x=>x.toString,result=>result.entityId).size==0)
    }

Scala is able to solve ambiguity but scalamock fails to solve it. Can somebody please help me?

Below is the error in scalamock tests.

Multiple markers at this line
	- ambiguous reference to overloaded definition, both method processDataFromStore in trait HBaseStoreProcessor of type (adapter: com.snc.sinet.hbase.StorageAdapter, 
	 tableName: String, metricId: Short, colFamilies: Array[Array[Byte]], startTime: Long, stopTime: Long, isAggregated: Boolean, validateEntityRowKey: com.snc.sinet.hbase.EntityRowKey 
	 => Boolean, filter: org.apache.hadoop.hbase.filter.Filter)List[com.snc.sinet.dataAccess.DataStoreResult] and method processDataFromStore in trait HBaseStoreProcessor of type 
	 (adapter: com.snc.sinet.hbase.StorageAdapter, tableName: String, metricId: Short, colFamilies: Array[Array[Byte]], startTime: Long, stopTime: Long, isAggregated: Boolean, 
	 validateEntityRowKey: com.snc.sinet.hbase.EntityRowKey => Boolean)List[com.snc.sinet.dataAccess.DataStoreResult] match expected type ?
	- ambiguous reference to overloaded definition, both method processDataFromStore in trait HBaseStoreProcessor of type (adapter: com.snc.sinet.hbase.StorageAdapter, 
	 tableName: String, metricId: Short, colFamilies: Array[Array[Byte]], startTime: Long, stopTime: Long, isAggregated: Boolean, validateEntityRowKey: com.snc.sinet.hbase.EntityRowKey 
	 => Boolean, filter: org.apache.hadoop.hbase.filter.Filter)List[com.snc.sinet.dataAccess.DataStoreResult] and method processDataFromStore in trait HBaseStoreProcessor of type 
	 (adapter: com.snc.sinet.hbase.StorageAdapter, tableName: String, metricId: Short, colFamilies: Array[Array[Byte]], startTime: Long, stopTime: Long, isAggregated: Boolean, 
	 validateEntityRowKey: com.snc.sinet.hbase.EntityRowKey => Boolean)List[com.snc.sinet.dataAccess.DataStoreResult] match expected type ?
	- Line breakpoint:DataAccessUtilTest [line: 54] - <init>(): com.snc.sinet.dal.DataAccessUtilTest

**Comment by pawel-wiejacha** [comment]
Closing as incomplete for now.
