### ISSUE TITLE
Ability to tell ScalaMock to ignore any interaction with mock

### ISSUE THREAD

**Issue by hipnoizz** [paulbutcher/ScalaMock#89]
Maybe I missed something but I coudn't find a way to tell ScalaMock to ignore any interaction with given mock. An example:

``` scala
package test

import org.scalamock.scalatest.MockFactory
import org.scalatest.{OneInstancePerTest, FunSuite}

trait Service {
    def service()
}

class Controller(val service: Service) {
    def doSomething() {
        service.service()
    }
    def doSomethingElse() {
        service.service()
    }
}

class ScalaTest extends FunSuite with MockFactory with OneInstancePerTest{
    val service = mock[Service]
    val controller = new Controller(service)

    test("testA") {
        (service.service _).expects()

        controller.doSomething()
    }

    test("testB") {
        // I would like to do something like ignores(service) here, because this test does not care about service.

        controller.doSomethingElse()
    }
}
```

I know that I can use `val service2 = stub[Service]` but then I need to duplicate whole objects construction process.

This 'pattern' comes from my usage of JMock and helps to not overspecify mocking objects.

**Comment by UrsMetz** [comment]
@pawel-wiejacha Any news on this issue? Started using ScalaMock a while ago and pretty some wanted to have this feature :-) as like the OP I know it from JMock.

**Comment by sahilsareen** [comment]
Any updates on this?

**Comment by suriyanto** [comment]
:+1:

What's the thought around this functionality?

**Comment by hipnoizz** [comment]
I returned to using JMock in my Scala projects, even with all these oddities that this combination brings. Still, would be happy to use more idiomatic solution. Judging from additional comments I think I'm not the only one interested in this functionality.

**Comment by barkhorn** [comment]
You can already stub on the method level, partially ignoring interactions this way, see below.
I don't think increasing the complexity of the codebase makes sense here, just to gain a little extra flexibility.
ScalaMock already supports `stub` and `mock` paradigms, and converting one to the other dynamically would make it much harder to manage internally (stateful in particular).
Fixtures already allow to ignore a whole mock as described above, and don't add that much verbosity either. They can be written as layered traits to avoid telescoping boolean constructor parameters.

```scala
trait Foo {
  def foo(i: Int): Unit
  def bar(i: Int): String
}

val m = mock[Foo]
m.foo _ stubs *
m.bar _ expects * returning "hi!" once()

m.foo(5)
m.foo(6)
m.foo(5)
m.bar(42) should be ("hi!")
```
