### ISSUE TITLE
NullPointerException using Scalamock 3.2.1 with ScalaTest and akka-testkit

### ISSUE THREAD

**Issue by traviskaufman** [paulbutcher/ScalaMock#91]
Hello!

First off, awesome library. We switched over to this from Mockito and have been really liking it so far!

We're running into an issue when using scalamock with scalatest and [akka-testkit](http://doc.akka.io/docs/akka/snapshot/scala/testing.html) where it seems that if a mock function is invoked within an actors `postStop` lifecycle hook, the code in `FakeFunction` that executes results in a `NullPointerException`.

## To Reproduce

Here is the minimum setup I could come up with to reproduce the problem

#### build.sbt

```scala
name := "foobar"

version := "0.1.0"

scalaVersion := "2.11.4"

scalacOptions ++= Seq("-unchecked", "-feature", "-deprecation")

scalacOptions in Test ++= Seq("-language:reflectiveCalls")

resolvers ++= Seq(
  "Typesafe Repository" at "http://repo.typesafe.com/typesafe/releases/"
)

libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.3.6",
  "com.typesafe.akka" %% "akka-testkit" % "2.3.6" % "test",
  "org.scalatest" %% "scalatest" % "2.2.1" % "test",
  "org.scalamock" %% "scalamock-scalatest-support" % "3.2.1" % "test"
)
```

#### src/main/scala/foobar/Thing.scala
```scala
package foobar

import akka.actor.{ Actor, Props }

trait Doer {
  def doSomething(): Int
  def close(): Unit
}

object Thing {
  type DoerMaker = () => Doer
  case object DoSomething
  case class SomethingDone(thing: Int)

  def props(dm: DoerMaker): Props = Props(classOf[Thing], dm)
}

class Thing(dm: Thing.DoerMaker) extends Actor {
  import Thing._

  private lazy val doer = dm()

  override def postStop() {
    doer.close()
  }

  def receive = {
    case DoSomething => {
      sender ! SomethingDone(doer.doSomething())
    }
  }
}
```

#### src/test/scala/foobar/ThingSpec.scala
```scala
package foobar

import akka.actor.ActorSystem
import akka.testkit.{ TestKit, ImplicitSender }
import org.scalatest.{ WordSpecLike, Matchers, BeforeAndAfterAll }
import org.scalamock.scalatest.MockFactory

class ThingSpec(_system: ActorSystem) extends TestKit(_system)
    with ImplicitSender with WordSpecLike with Matchers with BeforeAndAfterAll with MockFactory {

  import Thing._

  def this() = this(ActorSystem("ThingSpec"))

  override def afterAll {
    TestKit.shutdownActorSystem(system)
  }

  "A Thing" must {
    "send back SomethingDone with the result of doSomething() when sent DoSomething" in {
      val f = fixture
      (f.mockDoer.doSomething _).expects().returning(5)
      f.thing ! DoSomething
      expectMsg(SomethingDone(5))
    }
  }

  def fixture = new {
    val mockDoer = mock[Doer]
    val mockDoerMaker = () => mockDoer
    val thing = system.actorOf(Thing.props(mockDoerMaker))
  }
}
```

## Output

Here is what gets printed on the console when I run `sbt test` on the above project

![screen shot 2015-01-13 at 5 08 56 pm](https://cloud.githubusercontent.com/assets/1185269/5730301/f1d762e8-9b46-11e4-92be-bc90042d0bcd.png)

Notice that all the tests pass, but we get that NPE which seems to happen because in `Thing#postStop` we're calling `doer#close()`, which invokes the FakeFunction and therefore seems to result in a NullPointerException. Could this possibly be a threading issue? 

Let me know if you need any additional information. Any help is greatly appreciated!

**Comment by traviskaufman** [comment]
Solved my own problem. Had to mix in the `OneInstancePerTest` trait into my tests so that resources weren't shared between specs.

**Comment by paulbutcher** [comment]
Well done Travis—sorry I wasn't able to look at this before you worked it out for yourself.

**Comment by monktastic** [comment]
I'm having the same problem, though mine occurs from preStart. Mixing in OneInstancePerTest does not solve it.
