### ISSUE TITLE
mixing styles (or add when support to `mock`)

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#97]
I have an object that I'm mocking and it has a method that is polled a lot. I don't care about testing on when it is called, so I'd like to just fix it with a `when`. But I also want to do `expects` assertions on the same object.

It doesn't seem possible to be able to do this, but it would be very useful.

**Comment by paulbutcher** [comment]
If I understand you correctly, can't you use `anyNumberOfTimes` to achieve this?

    (m.someFunc _).expects(*).returning("a return value").anyNumberOfTimes

There's a (not very well documented) `stubs` function for which is syntactic sugar for `anyNumberOfTimes`:

   (m.someFunc _).stubs(*).returning("a return value")

Does this give you what you want?

**Comment by fommil** [comment]
cool, thanks, that does help!
