### ISSUE TITLE
do a verify after a expectation first

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#98]
When writing async tests, it is possible that an unexpected call may be made to a mock, in a way that is masked by the async nature of the object being tested.

With "expectation first" style testing, this means that the unexpected calls are only visible in the logs.

I'd like to be able to do a catch-all call at the end of my test to basically assert that there wasn't anything unexpected, and to tell me what it was if something failed.

Is that something you could support? (or is it something I missed in the docs)

**Comment by fommil** [comment]
(maybe I should really be using stubs... problem might go away)

**Comment by fommil** [comment]
I worked around this with  https://groups.google.com/forum/#!topic/akka-user/0Ene7WaDyng

So any failed expectations (in another thread) are caught by the fact that the actor dies.

**Comment by paulbutcher** [comment]
So what you describe (the catch-all at the end of your tests) is basically exactly what ScalaMock already does (see the `withExpectations` method in `MockFactoryBase`). Your problem, I guess, is that the unexpected call is happening *after* this has happened?

I'm not really sure what we could do about that, although I'm open to suggestions if you have any?

**Comment by fommil** [comment]
aaah, I didn't see the `withExpectations` scoper. I'll add that! Although I think it was probably wise to put a stopping supervisor on the test actors anyway. I'm not entirely sure why the default test supervisor is different to the default guardian.

**Comment by paulbutcher** [comment]
You don't need to add `withExpectations`—it happens automagically as long as you haven't set `autoVerify` to `false` (see `withFixture` in `AbstractMockFactory`).

**Comment by fommil** [comment]
Hmm, that is interesting. I'm definitely seeing unexpected messages in the logs and tests passing. I'll be safe and add it. Does it have a memory boundary to force a sync of everything across threads?

**Comment by paulbutcher** [comment]
Adding it twice will definitely not cause anything good to happen.

My guess is that the unexpected calls are happening *after* `withExpectations` has completed. Which would cause exactly what you're seeing—the test passes because there *are* no unexpected calls at that point, and then you get a subsequent failure in the async thread.

**Comment by paulbutcher** [comment]
Oh - regarding your question about barriers, yes this is intended to work fine (although, as we all know, this kind of thing is prone to error, so it's quite possible that something's slipped through). See, for example, the `handle` method in `OrderedHandlers`

**Comment by fommil** [comment]
right, ok, maybe it is a timing thing (although I'm not 100% convinced of that because of the nature of the failure). Certainly something to be mindful of.

This is my work code, but we have a similar use case in ENSIME where we lose the ability to throw the expectation failure because it happened in another thread. It would be good to be able to say at an arbitrary point "right, check if we seen anything we shouldn't have". Those sorts of failing tests usually mean hunting through the logs instead of it appearing in the console.

**Comment by paulbutcher** [comment]
OK, that you can achieve by setting `autoVerify` to `false` and calling `verifyExpectations` yourself, wherever you want. But I very much doubt that this will help—the current behaviour basically calls `verifyExpectations` at the end of your test, which is pretty much what you want, yes?

**Comment by fommil** [comment]
In my work code, yes, auto-verify sounds like what I want. For the ENSIME code, `false` might be good.

**Comment by paulbutcher** [comment]
Can you explain why? `autoVerify` being `false` only allows you to move the verification earlier. We find that useful in some of ScalaMock's internal tests, but I struggle to see how it would be helpful apart from testing the framework itself.

**Comment by fommil** [comment]
yes, that's exactly what we want to do in ENSIME. When testing the protocol layer we will throw a timeout exception if we don't receive a response to a query. That is the exception that fails the test, so the mock expectation never gets seen. What we'd like to do is to check if we received what we wanted and if that fails do pre-emptive `verifyExpectations` incase that was the problem.... all the time wrapped in a `withExpectations` so that any other expectation failures are caught.

btw
```scala
  private def verifyExpectations() {
     ....
  }
```
... `private` :cry:  It also seems to clear the expectation list. I'd like to verify just the messages that we received, not necessarily the missing ones (yet). We can probably refactor so that we do the full verification here, but being private the option is not available.

I've read the MockFactory code now and I can see all this autoverify logic, so I understand the lifecycle of the tests more clearly. It must be a timing issue on my work code, otherwise it makes no sense.

**Comment by paulbutcher** [comment]
Oh, so in the ENSIME case, this isn't a test that's not failing when it should. It's just that it's failing with an exception instead of a broken expectation? Perhaps the right solution is to catch the exception yourself? Something along these lines?:

    var Exception thrown = _
    withExpectations {
        try {
            ... system under test...
        } catch {
            case TimeoutException e => thrown = e
        }
    } // expectations will be verified here
    if (thrown)
        // do something with exception here

**Comment by fommil** [comment]
ooh, that might work, thanks! @rorygraves this would make our protocol stuff cleaner

**Comment by fommil** [comment]
```scala
var Exception thrown = _
```

I'm guessing you weren't in "Scala land" today :wink:

**Comment by paulbutcher** [comment]
(blush)

**Comment by fommil** [comment]
you've been writing Java, go on, admit it! :stuck_out_tongue:
