### ISSUE TITLE
remove an `atLeastOnce` expectation?

### ISSUE THREAD

**Issue by fommil** [paulbutcher/ScalaMock#99]
I am mocking an I/O access object which has a method something like "getLatestNumber".

I don't really care about testing how many times it is called, so I put `atLeastOnce` on it, but in some of my tests I want to *change* the expectation in the middle of a test to mock out a change in state.

The problem is that the first expectation always trumps and my replacement is ignored. Is this intentional? Is there a workaround?

I am working around with `onCall` but that means I have to store my expectation in a mutable variable at the test class level because of the way the code is organised, which is a bit nasty.

**Comment by paulbutcher** [comment]
Let me make sure that I understand your use case properly. You have a mock thats shared between a number of tests (in a fixture?). For most of these tests, you want to set an `atLeastOnce` expectation, but for some, you don't?

This isn't something that ScalaMock supports—any expectations you set on a shared mock, should be shared by all tests that use it. Those that aren't shared between all tests, should be setup individually in the tests themselves. So this means that you have one of the following choices:

* Don't set an expectation on this particular method in the fixture, do it in each of the tests individually
* If this results in too much duplicated code, consider implementing a method that is called by each tests to set the common expectations.
* If it's just one test that has different expectations, don't use the shared mock in that test. Or if there are multiple tests, perhaps have a second shared mock for those tests?

**Comment by fommil** [comment]
no, not shared. I instantiate a new mock for each test. The use case is that I want to dynamically change the response of one method to simulate changing I/O state.

**Comment by paulbutcher** [comment]
Oh! Got you. And you can't determine that this method is "the one" from the arguments passed to it or the number of calls beforehand?

**Comment by fommil** [comment]
no, the number of calls beforehand is arbitrary. It's more that "now we've reached this part of the code we want to change the state". It's quite timing sensitive because it's all about querying a pull-based API and making it look like an async source with backpressure.

**Comment by fommil** [comment]
a `clearExpectations` on that method would actually help.

**Comment by paulbutcher** [comment]
I think your `onCall` approach is the right solution in this case. This is a long way away from a "normal" kind of test :-)

**Comment by fommil** [comment]
bugger :smile: Oh well, it just means we can't parallelise this suite
